### ISSUE TITLE
Make closeOnClickOutside respect closeOnClickBackdrop?

### ISSUE THREAD

**Issue by shiptoncraig** [arkon/ng-sidebar#101]
I need to be able to close the sidebar, when clicking outside of it, only if the backdrop is not showing.

Since the backdrop sits within the "outside" of the sidebar, we could make `_onClickOutside` respect the closeOnClickBackdrop flag?

In other words, the possible scenarios would be as so (the new one in bold):

closeOnClickOutside -> false
closeOnClickBackdrop -> false
showBackdrop -> false
clicking outside = does nothing, sidebar remains open without backdrop

closeOnClickOutside -> true
closeOnClickBackdrop -> false
showBackdrop -> false
clicking outside = closes sidebar

closeOnClickOutside -> true
closeOnClickBackdrop -> true
showBackdrop -> false
clicking outside = closes sidebar

**closeOnClickOutside -> true**
**closeOnClickBackdrop -> false**
**showBackdrop -> true**
**clicking outside = does nothing as we have a visible backdrop overlaying "outside" which cannot be closed by clicking on it**

closeOnClickOutside -> true
closeOnClickBackdrop -> true
showBackdrop -> true
clicking outside = closes sidebar

What are your thoughts?

**Comment by arkon** [comment]
I would expect `closeOnClickOutside` to take precedence there and close the sidebar regardless since you are clicking outside.

**Comment by arkon** [comment]
I guess I've slept on this for a few days now, but I still feel the same way so I'm just going to leave it as is.
