### ISSUE TITLE
Sidebar animation is choppy

### ISSUE THREAD

**Issue by Akkusativobjekt** [arkon/ng-sidebar#103]
Today I upgraded my Angular 2 project to angular 4. Therefore  also upgraded from ng2-sidebar from 3.2.1, to v6.0.0 (ng-sidebar). After adjusting the sidebar to the new version, I noticed that the animation is now very choppy and simply does not look smooth. 

This gifs shows how the sidebar currently performs. The mode is set to "over" and dock is set to "true". Mode "push" does not make any difference, but if dock is disabled, the animation looks smooth again.
![new](https://user-images.githubusercontent.com/5674024/27675765-9211f2f0-5cab-11e7-823c-dd74a11b4cc5.gif)
This gifts shows version 3.2.1, the animation is much more smooth, the sidebar is set to "dock"
![old](https://user-images.githubusercontent.com/5674024/27675766-921f4220-5cab-11e7-8f03-d5a121e73e43.gif)

The speed of the clicks in both gifs may be different, but the animation of the "old" version does always look smooth, even if you click faster. 

I did not change any css between the two version. The gifs are recored in Firefox 54, but in Chrome 59 the issue appears, too. I also noticed that when you look closely at the demo project, the problem appears (in Chrome and FF), too, but with the white backgroundcolor it is harder to notice.

**Comment by arkon** [comment]
Fixed in v6.0.1.

**Comment by Akkusativobjekt** [comment]
Thank you very much for the super fast fix. In my opinion the current animation (v6.0.1.) looks even better than the old one (v3.2.1).

**Comment by Rwin90** [comment]
i still have this problem

**Comment by alishenriques** [comment]
Hi!
I'm really sorry to comment in a closed issue, but I'm using **ng-sidebar v.7.2.0** with **Angular v5.2.0** and facing a very similar issue when the slide is set to _'open'_. The animation is choppy again and bouncing sometimes.
The only configurations I'm using are _position_ set as _'right'_ and _mode_ set as _'slide'_.
I'm testing in **Chrome v67** and **Firefox v61**, in both of them the issue happens, but in Firefox it's even more evident. The problem appears at the demo project too. 
I already tryed to overwrite the animations on SASS but still no better effects.
I'm still trying to find a way to fix it. But in the meantime, I'd like to know if there's some way to help me with this issue. 

Thank you so much for your attention. :)

**Comment by arkon** [comment]
CSS transitions are prone to performance issues, unfortunately. I'm not sure if there's a good way to really "fix" it.
