### ISSUE TITLE
Sidebar not showing up

### ISSUE THREAD

**Issue by vgosain91** [arkon/ng-sidebar#105]
I tried integrating sidebar as per the readme instructions but nothing is showing up.

**Comment by arkon** [comment]
You need to provide more information. What version of ng-sidebar and Angular are you using? What does your template look like? Are there errors in the console?

**Comment by vgosain91** [comment]
angular 4, angular-cli - 1.0.2, ng-sidebar - 6.0.1 . I tried copy pasting the exact code from readme to my app component but nothing comes up html file shows ng -sidebar-x tags but nothing comes up.

**Comment by arkon** [comment]
Does #100 help?

**Comment by vgosain91** [comment]
unfortunately, not

**Comment by arkon** [comment]
What do you see in DevTools? Are the components there, but seemingly just without any height?

**Comment by vgosain91** [comment]
the components are there and for ng-sidebar-container, the height is 100%.

**Comment by arkon** [comment]
If the components are there and you can see all the content within them in DevTools, it's likely an issue with styles. It's hard for me to pinpoint the issue without seeing it, unfortunately.

**Comment by TcQPAD** [comment]
The components are there but the base/class styles are just not applied to the elements 

![bug-sidebar](https://user-images.githubusercontent.com/17066590/27770530-84ccc556-5f40-11e7-93f0-32d5627871e1.PNG)

**Comment by arkon** [comment]
Looks fine to me. I'm assuming you didn't copy the regular Sass styles from the demo, so the base styles of `.demo-sidebar` aren't there. The component doesn't have any base styles beyond the positioning, so you can style it yourself.

**Comment by TcQPAD** [comment]
Well.. You're right! My bad there
