### ISSUE TITLE
MacOS and MobileDevices Not Working 

### ISSUE THREAD

**Issue by samir-h** [arkon/ng-sidebar#109]
Hi, I am using ng-sidebar on a project, and it works really good on Chrome,Firefox,Opera and Edge . But I am having problems on MacOS(Safari,Chrome) , and on mobile devices iOS and Android. 
Am I having conflicts with any other library, or what seems to be the problem ? 
I tried everything but could not find a solution, would appreciate any idea ...

**Comment by arkon** [comment]
Generally, [the demo](https://echeung.me/ng-sidebar/) is the baseline for whether it works in different browsers/on different platforms. It works fine for me in Safari/Chrome on macOS and on Android, though I haven't tested on iOS.

Hard to say what's wrong with it for you since I can't see it.

**Comment by samir-h** [comment]
This is my code for sidebar : 
```
<ng-sidebar-container>
  <ng-sidebar class="rc-sidebar" [(opened)]="opened" [position]="'right'" #sidebar [closeOnClickOutside]="true" [autoFocus]="false" [keyClose]="true">
      <a (click)="sidebar.close()" class="closebtn"  style="display: inline">&times;</a>
      <a href="#" class="user-logged"><img src="../../assets/img/tomhardy.jpg" class="img-profile img-circle"></a>
      <button md-icon-button [mdMenuTriggerFor]="menu" class="pull-right language_button">
        <md-icon *ngIf="currentLang=='en'"><img src="../../assets/img/england_24.png"> </md-icon>
        <md-icon *ngIf="currentLang=='se'"><img src="../../assets/img/sweden_24.png" > </md-icon>
      </button>
      <md-menu #menu="mdMenu">
        <button md-menu-item (click)="changeLanguage('en')" >English</button>
        <button md-menu-item (click)="changeLanguage('se')">Svenska</button>
      </md-menu>

      <div class="side-menu-items">
        <label class="user-name">Leart Zogjani</label>
        <label class="user-privilege">admin user</label>
        <label class="user-edit" (click)="showEdit()">{{'edit profile'| translate}}</label>
        <label class="user-edit">{{'log out'| translate}}</label>

        <div class="side-menu-list">
          <ul>
            <li> <a [routerLink]="['/units']" class="text-uppercase">units?</a> </li>
            <li> <a [routerLink]="['/reports']" class="text-uppercase">{{'reports'| translate}}</a> </li>
            <li> <a [routerLink]="['/extensions']" class="text-uppercase">{{'extensions'| translate}}</a> </li>
            <li> <a [routerLink]="['/users']" class="text-uppercase">{{'users'| translate}}</a> </li>
            <li> <a [routerLink]="['/dashboard']" class="text-uppercase">{{'dashboard'| translate}}</a> </li>
          </ul>
        </div>
      </div>
  </ng-sidebar>
  <div style="clear:both;"></div>
```

and this is where i open the sidebar : 
`<a (click)="sidebar.open()" ><i class="fa fa-bars"></i> </a>` 

idk why it doesnt work in MacOs , or mobile devices , since i get no error message

**Comment by arkon** [comment]
Yeah, I really can't tell. You'll need to debug it yourself somehow by looking at the sidebar element(s) in the element inspector and seeing if anything weird's going on.

What exactly doesn't work though? It just doesn't open?

**Comment by samir-h** [comment]
The sidebar elements seem to open, but they are not shown . If i do inspect element , and set the sidebar width to 350px for example , it is visible but doesn't shrink after i close it . So i think that the problem is in the transition .

**Comment by bkbaheti** [comment]
I somehow could not reproduce this error. @samir-h will you give some more details
