### ISSUE TITLE
Unable to use sidebar based on readme

### ISSUE THREAD

**Issue by vandensd** [arkon/ng-sidebar#110]
I'm generating a new angular app from the latest cli and using the documentation verbatim in the readme.  Only caveat is using app.module for the Import.  I'm not able to see the toggle button or see the sidebar by manually setting the backing variable to true.

The only changes I make after generating the app is editing the app.component html and ts per the documentation in the readme.

Is this documentation out of date?

**Comment by arkon** [comment]
I suspect #100 solves your problem. I need to add that to the readme.

**Comment by vandensd** [comment]
Appreciate the quick reply.  The styling to enforce 100% w/h was the issue.  I will close the ticket.
