### ISSUE TITLE
Styling changes not working

### ISSUE THREAD

**Issue by rbwrightjr91** [arkon/ng-sidebar#111]
I'm trying to change the background color of the sidebar, as it is just clear at the moment. The changes I make in my css file don't have an effect on the sidebar element. However, they do work on the container element (like making the height 100vh). I've scoured the issues dealing with this and none of the fixes work. If it matters, I made a sidebar component that is called inside app.component.html.

version: 6.0.1

Here is app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { SidebarModule } from 'ng-sidebar';

import { AppComponent } from './app.component';
import { SidebarComponent } from './sidebar/sidebar.component';

@NgModule({
  declarations: [
    AppComponent,
    SidebarComponent,
  ],
  imports: [
    BrowserModule,
    NgbModule.forRoot(),
    SidebarModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

sidebar.component.ts:
```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  private opened: boolean = false;

  constructor() { }

  ngOnInit() { }

  private toggleSidebar() {
    this.opened = !this.opened;
  }

}
```

sidebar.component.html:
```
<ng-sidebar-container>
  <ng-sidebar [(opened)]="opened">
    <p>Sidebar</p>
  </ng-sidebar>
  <div ng-sidebar-content>
    <button (click)="toggleSidebar()">Toggle</button>
  </div>
</ng-sidebar-container>
```

and sidebar.component.css:
```
ng-sidebar-container{
  height: 100vh;
}

/* I've tired .ng-sidebar, :host ng-sidebar, 
    :host /deep/ ng-sidebar and many combinations of them */
ng-sidebar{
  background-color: #fff !important; 
}
```

**Comment by rbwrightjr91** [comment]
Tested to make sure I was accessing the write element, and adding a text color to ng-sidebar css changes the text color.

**Comment by rbwrightjr91** [comment]
Ok, changing the css target to `ng-sidebar [_ngcontent-c1]` adds the background, but only around the content and doesn't extend the full page. That's a different issue that I'm sure I can figure out, though.

**Comment by arkon** [comment]
`:host /deep/ .ng-sidebar` should work. If not, add your own class to the sidebar element with `[sidebarClass]` and target that.

**Comment by rbwrightjr91** [comment]
Hm, I thought I tried that combination but apparently not. Worked. Thanks!
