### ISSUE TITLE
opened initially shows sidebar even if false

### ISSUE THREAD

**Issue by Ketec** [arkon/ng-sidebar#112]
[opened]="false"
[(opened)]="state" / public state: boolean = false;

In both cases it initially shows sidebar on page load for a moment - until change detection i assume.

If i remove the opened from attributes, it won't initiall show (and well  icant show it ether).

**Comment by ebtroy** [comment]
This is happening to me as well.

**Comment by arkon** [comment]
I can't seem to reproduce this. Are there any other options that you've used?

**Comment by Ketec** [comment]
```
                <ng-sidebar
                    [(opened)]="settingsOpened"
                    position=right
                    [autoFocus]=false
                    [trapFocus]=false
                    [mode]="'over'"
                >
```
settingsOpened is false (settign it false in there still causes the bug).

**Comment by arkon** [comment]
I still can't seem to reproduce the issue. Do you have some styles for the sidebar too?

**Comment by Ketec** [comment]
```
.ng-sidebar {
    box-shadow: -4px 0px 3px -1px #e5e5e5;
    background-color: #f3f3f4 !important;
    overflow: hidden !important;
    position: absolute !important;
    display: -webkit-box;
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    flex-direction: column;
    z-index: 100 !important;
}

ng-sidebar-container {
    flex-basis: 100%;
    width: auto !important;
}
```

**Comment by kotmatpockuh** [comment]
the same issue :(

**Comment by Ketec** [comment]
Bit of testing and it seems like animations are to blame:
```
:host /deep/ .settings-module .ng-sidebar--animate[_ngcontent-c6] {
    -webkit-transition: none !important;
    transition: none !important;
}

```
Quick override to this and the bug is gone - but so is the animation. It seems like the animation is triggered in the beginning and in some cases (larger app, slower initial load and wider sidebar), it becomes noticeably visible.

Perhaps visibility: hidden might be needed for hidden/visible behaviour on top of pushing it off screen?

**Comment by arkon** [comment]
Thanks for the investigation and suggestion, @Ketec . I've published v6.0.4 with a change based on yours.

**Comment by RezaRahmati** [comment]
Same for me, is this issue solved?
![slider](https://user-images.githubusercontent.com/10086092/45593520-7bca9480-b956-11e8-9d87-9ab6ae0fd037.gif)

**Comment by arkon** [comment]
Open another issue. It should be fixed though, unless you can reproduce the problem in a basic setup.

**Comment by RezaRahmati** [comment]
I found a workaround
```
animate = false;
  ngOnInit() {
    setTimeout(() => {
      this.animate = true;
    }, 1000);
  }
```

`<ng-sidebar [(opened)]="sideOpen" [position]="'right'" [animate]="animate">`

**Comment by ef32** [comment]
This issue seems to have resurfaced in the latest version

**Comment by jomolmj** [comment]
Anybody solved this issue?

**Comment by lasantha57** [comment]
@RezaRahmati is right! Problem is with the `[animate]="true"`. Either we can remove it or this workaround would work.

```
  animate = false;

  ngOnInit() {
    setTimeout(() => {
      this.animate = true;
    });
  }
```
