### ISSUE TITLE
Add possibility to close/open sidebar from any other inner component 

### ISSUE THREAD

**Issue by kotmatpockuh** [arkon/ng-sidebar#113]
`router-outlet` do not support any input/output events, so, please add (or give an idea) how to close/open sidebar from any inner component, using Sidebar service, now i get: `Cannot read property 'nativeElement' of undefined`

**Comment by arkon** [comment]
The sidebar service was removed a while ago.

Assuming you mean something inside the sidebar itself when you say "inner component", you ought to be able to use the `closeSidebar`directive, but I'll need to double check if that works.

**Comment by kotmatpockuh** [comment]
ok,
for example in my app.html I have:

```
<ng-sidebar-container>
  <ng-sidebar
    [(opened)]="openedSidebar"
    [mode]="modeSidebar"
  </ng-sidebar>
  <ng-container ng-sidebar-content>
    <router-outlet></router-outlet>
  </ng-container>
</ng-sidebar-container>
```

and in any route (component, which is appended into router-outlet) I wanna to have an opportunity to close sidebar

**Comment by arkon** [comment]
Ah, you mean from the container's contents. `closeSidebar` won't work for that -- you'll likely need to hold a reference to the sidebar somewhere and work with that.

**Comment by kotmatpockuh** [comment]
it's impossible...
due to layout (for example if i have public and secure routes): such component do not work with shared services

**Comment by kotmatpockuh** [comment]
any ideas maybe?

**Comment by arkon** [comment]
> such component do not work with shared services

What do you mean? I'm sure you can have some sort of "global" service that's injected everywhere. You could even just forgo the Angular route and have a regular class somewhere that's responsible for holding the sidebar reference.
