### ISSUE TITLE
unable to override ng-sidebar__backdrop class property

### ISSUE THREAD

**Issue by dattatrey93** [arkon/ng-sidebar#114]

**Comment by arkon** [comment]
Did you try `:host /deep/ .ng-sidebar__backdrop`?

**Comment by dattatrey93** [comment]
No, i tried with !important but that hadn't worked. but now working with /deep/ .ng-sidebar_backdrop. Thanks @arkon

**Comment by pleinonen** [comment]
Unfortunately this does not seem to work for me (using Angular 4.4.4). Tried all these combinations:

`:host ::ng-deep .ng-sidebar__backdrop {
  opacity: 0;
}`
`::ng-deep .ng-sidebar__backdrop {
  opacity: 0;
}`
`:host /deep/ .ng-sidebar__backdrop {
  opacity: 0;
}`
`/deep/ .ng-sidebar__backdrop {
  opacity: 0;
}`

Component's internal style still takes precedence over these declarations. Could you make this property parametrised as we all know that deep selectors are going to be depricated anyway, or perhaps help to find other way to override styles?

**Comment by arkon** [comment]
@pleinonen To be honest, I kind of hate how Angular's style encapsulation works.

It might be easier to just set a `[backdropClass]` input:

```html
<ng-sidebar-container [backdropClass]="'my-backdrop'">
  ...
</ng-sidebar-container>
```

```css
.my-backdrop {
  opacity: 0 !important;
}
```
