### ISSUE TITLE
Angular2 - Wrapping sidebar in a div which gets conditionally hidden/shown does not work

### ISSUE THREAD

**Issue by ohtwadi** [arkon/ng-sidebar#116]
Hello!

I'm having issues displaying the sidebar when it's wrapped in a div which is toggled to display once I have all the needed data. 

Template:
```html
<div *ngIf="isDataAvailable; else elseBlock">
    <div>This shows up</div> <!-- This shows up once isDataAvailable gets set to true in the component -->
    <ng-sidebar-container>
        <!-- A sidebar -->
        <<ng-sidebar [(opened)]="_sideBarOpened" position="right">
            <div>sidebar</div>
                
        </ng-sidebar>

        <!-- Page content -->
        <div ng-sidebar-content>
            <div>content</div>
        </div>

    </ng-sidebar-container>
</div>
<ng-template #elseBlock>Loading....</ng-template>
```

Part of the component:
````javascript
ngOnInit() {
this.schedulerService.getResources()
      .subscribe(resources => {
            this.resources = resources;
            this.isDataAvailable = true;
          }
}
````

**Comment by arkon** [comment]
Does #100 help?

**Comment by ohtwadi** [comment]
Unfortunately no.  
I was using sidebar successfully over the last month so I think the setup part is fine. Just today I encapsulated the entire thing with <div *ngIf and it stopped showing up. 

Also, I would like to point your attention to these two lines. 
````html
<div *ngIf="isDataAvailable; else elseBlock">
    <div>This shows up</div>
````
The 'This shows up' text gets displayed in the browser once isDataAvailable is set to true but sidebar piece does not. 

I hope that sheds some further light on what I'm seeing. Thanks!

**Comment by arkon** [comment]
Yeah, I was just hoping it'd be the easy fix. I'll check it out later today.

**Comment by ohtwadi** [comment]
Thank you, much appreciated.

**Comment by arkon** [comment]
@ohtwadi Are you sure you don't just need to add a height to that new surrounding `div` with the `ngIf`?

**Comment by ohtwadi** [comment]
Thanks for pointing out my extraordinarily silly mistake.
