### ISSUE TITLE
window scroll event

### ISSUE THREAD

**Issue by kmathyPRO** [arkon/ng-sidebar#117]
Hi,

Firstly, thanks for the plugin, it seems very nice.
But I have one problem and maybe you can help me:

Before using your plugin, I had a directive checking the window scroll to fix a header
`this.scrollSubscription = Observable.fromEvent(window, 'scroll').subscribe(e => {
      this.onScroll();
    });`

It works perfectly.

However, once I put ng-sidebar-content, the Observable don't trigger anymore.

Do you know the problem? A workaround? I tried to move the directive, target another element in the page... But scroll event is not triggered

Thanks in advance

**Comment by arkon** [comment]
Try observing the actual `[ng-sidebar-content]` element instead of `window`.

**Comment by kmathyPRO** [comment]
Unfortunately not, I tried in HTML
`<div class="tt-main" ng-sidebar-content headerSticker>`
and in directive
`this.scrollSubscription = Observable.fromEvent(this.el.nativeElement, 'scroll')`

where this.el.nativeElement represents the div

**Comment by arkon** [comment]
Whoops, you'll need to actually target its parent element (i.e. the element with class "ng-sidebar__content").

**Comment by kmathyPRO** [comment]
It works! Thanks a lot!

**Comment by shabbir-dhangot** [comment]
I have added window.scrollTo(0, 0) on many place of project.
Can you give exact code for that. Seems to not working for me.

**Comment by shabbir-dhangot** [comment]
@kmathyPRO Can you add your code or let me know where I need to change my code.

**Comment by stephenasamoah** [comment]
@arkon @kmathyPRO  Can you guys kindly provide some more insight into this? I notice @shabbir-dhangot also got stuck. I am fairly new to Angular and tried creating a reference variable on the `<div #sampleVarialbe ng-sidebar-content>`, but this, like @shabbir-dhangot's example didn't work. 

I really need to get this working, so please shed some more light on this issue. Thanks.

**Comment by arkon** [comment]
You want the parent element, i.e. `this.sampleVariable.nativeElement.parentElement`.

**Comment by stephenasamoah** [comment]
Thanks, it works.

**Comment by Daskus1** [comment]
Is there another way to solve this? 
I have a nested component tree inside `<router-outlet>` which is child of `ng-sidebar-content`. I would like to keep the component tree independent of ng-sidebar, as it might be used in other projects where sidebar is not used. Thus I would like to simply call something like `fromEvent(window, "scroll")`.
