### ISSUE TITLE
Sidebar with icons and icons visible even when sidebar is closed

### ISSUE THREAD

**Issue by rakeshkalra1983** [arkon/ng-sidebar#118]
Hi

I loved the sidebar you created, can you help me update your sidebar to have icons, and icons are visible even when sidebar is closed?

Thanks in advance.

**Comment by arkon** [comment]
You can use the `dock` option to keep part of the sidebar visible when closed, something like this:

```html
<ng-sidebar [opened]="_opened" [dock]="true">
  <div *ngIf="_opened;else closed_content">
    <!-- Opened content -->
  </div>
  <ng-template #closed_content>
    <!-- Closed content -->
  </ng-template>
</ng-sidebar>
```

You can also target the [various CSS classes](https://github.com/arkon/ng-sidebar#sidebar) to show/hide things appropriately.
