### ISSUE TITLE
Scrolling is quite hard in responsive devices

### ISSUE THREAD

**Issue by karamjeetsinghkst** [arkon/ng-sidebar#119]
Hi !
Am using ng-sidebar in my angular 4 project. Its working fine except one thing and that is responsive scrolling. I checked your demo link  https://echeung.me/ng-sidebar/  it also has same issue. Scrolling is not so smooth as on desktop. Please suggest something to get rid of it.

Thanks

**Comment by arkon** [comment]
Do you mean scrolling is difficult on phones?

**Comment by karamjeetsinghkst** [comment]
Hi,
It is not as smooth as desktop devices. Please check your demo link scrolling and other sites scrolling on mobile devices then you will find the issue.

Thanks

**Comment by PatrykTucki** [comment]
I confirm, scrolling was smooth on 4.2.2, currently it's not.

**Comment by urvesh21** [comment]
use  "**-webkit-overflow-scrolling: touch**" in **.ng-sidebar__content** class.

**Comment by arkon** [comment]
Added `-webkit-overflow-scrolling: touch` as per @urvesh21 's suggestion in v6.0.3.
