### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by pieterlouw1974** [arkon/ng-sidebar#121]
Good day

I had to set this in html
<ng-sidebar-container style="position: static;">
if not the screen is backgroud colour

**Comment by arkon** [comment]
Does #100 help?

**Comment by pieterlouw1974** [comment]
Ive tried

 <ng-sidebar-container style="height: 100%;">

<ng-sidebar-container style="position: static;"> => this still works for me.

Thanks

**Comment by Assdi** [comment]
style="position:static" works  for me  
thanks
