### ISSUE TITLE
Prevent auto-select of first link in sidebar

### ISSUE THREAD

**Issue by iskandarreza** [arkon/ng-sidebar#122]
Is there a way to prevent the first link available in the sidebar from being selected in focus when the sidebar is opened?

If you test any of the demos, or deploy a quick test yourself, you'll notice that the first available link in the sidebar will be brought into focus.  Right now I'm working around this by having it auto-select a [x] div that toggles the sidebar to be closed but I'd rather not have that div at all if possible.

**Comment by arkon** [comment]
`[autoFocus]="false"`

**Comment by iskandarreza** [comment]
You know what, my bad. I did not notice the autoFocus option until right after posting this.
