### ISSUE TITLE
[sidebarClass]="'demo-sidebar'" not Applied.

### ISSUE THREAD

**Issue by priyaragavan** [arkon/ng-sidebar#123]
I have setup all thing as well as in the documentation. It's working nice, but the demo-sidebar class not applied for the sidebarClass property. i got the following output in the over mode,

![screen1](https://user-images.githubusercontent.com/30138058/31314859-13959774-ac29-11e7-8f1d-16def5ce9fd8.PNG)
and,
![screen2](https://user-images.githubusercontent.com/30138058/31314873-1c011b04-ac29-11e7-8995-59d94e5a2e66.PNG)

**Comment by arkon** [comment]
There's not enough info for me to know what's wrong.

- What does your template look like?
- Are there errors in the console?
- Do you see the class being applied on the element in dev tools?
- Are you just running the demo locally with no changes?

**Comment by priyaragavan** [comment]
1. I use your demo template, as it is.
2. No errors displayed in console
3. The demo-class not found, but if i manually add the following style in the dev tools,
    aside.demo-sidebar.ng-sidebar--animate.ng-sidebar.ng-sidebar--opened.ng-sidebar--left.ng-sidebar--over {
    background: white;
    box-shadow: 0 0 8px #888;
    padding: 2em 2em;
},
i got the following result,
![screen3](https://user-images.githubusercontent.com/30138058/31326569-28fe5566-ace6-11e7-91f4-062f7a618c2d.PNG)
4. I Just add Material Design for buttons, except nothing else changed.

**Comment by arkon** [comment]
Is this using the latest code from GitHub?

**Comment by priyaragavan** [comment]
Yes, @arkon .

**Comment by arahmanali** [comment]
same for me

**Comment by arkon** [comment]
Can you provide me with the following info?

- Browser version
- Angular version
- ng-sidebar version

**Comment by arahmanali** [comment]
Mine:
- Chrome Version 61.0.3163.100
- Angular v4.4.5
- ng-sidebar v6.0.4

**Comment by priyaragavan** [comment]
- Chrome Version 61.0.3163.100
- Angular version 4.4.4 
- ng-sidebar v6.0.2

**Comment by arkon** [comment]
I can't seem to reproduce this, even with the exact same versions as @arahmanali .

So from what I'm understanding, you're just doing something along the lines of the following, right?

- Cloning/downloading a copy of this ng-sidebar repo
- Running `npm install && npm run build` in the root `ng-sidebar` directory
- Going to the `demo` directory and running `npm install && npm start`

**Comment by priyaragavan** [comment]
No, i didn't do that. Please check my code my repository "priyaragavan/ng-sidebar-demo" and give me some suggestion to solve this issue.

**Comment by arkon** [comment]
@priyaragavan It's because you included the styles as part of the `AppComponent`, so it's associating the `.demo-sidebar` CSS class with that component instead with Angular's emulated encapsulated styles. My demo just includes it as a regular `<link>`.

**Comment by priyaragavan** [comment]
Ok @arkon, Thank You.

**Comment by arahmanali** [comment]
i was able to change the style (in my app.components.scss) with the help of
`:host /deep/ .ng-sidebar`
but i have heard soon this is going to be obsolete,
do you guys know the new way?

**Comment by nissenJulia** [comment]
Could you maybe ellaborate further on what you mean with your answer @arkon ? I am facing the same problem that the `.demo-sidebar` CSS class styles are not applied to the element. I looked through your repository but could not find where you included the styles as a regular `<link>`? I'm sorry if I might be overlooking something fairly simple here.
