### ISSUE TITLE
Closeonclickoutside not working correctly

### ISSUE THREAD

**Issue by ShrekTheHumper** [arkon/ng-sidebar#126]
Hello,
I am experiencing a bug with closeOnClickOutside. It says in the docs it should be a boolean, but no matter what i have inside it, it counts as true. If i leave it empty it will count as false.

**Comment by arkon** [comment]
How are you passing in the value?

**Comment by ShrekTheHumper** [comment]
So if i do it like this `closeOnClickOutside=""` it will be disabled.
If i do it any of the following ways it will be enabled:
`closeOnClickOutside="true"
closeOnClickOutside="false"
closeOnClickOutside="*some variable*"`

**Comment by arkon** [comment]
You're passing in a string. Try doing `[closeOnClickOutside]="true"`>

**Comment by ShrekTheHumper** [comment]
That solves the issue. Thank you :)
