### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by merihs** [arkon/ng-sidebar#127]
I get installation error using npm version 5.5.1
Node Version : v8.9.0
npm Version : 5.5.1

npm ERR! Cannot read property '0' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user008\AppData\Roaming\npm-cache\_logs\2017-11-07T21_28_31_839Z-debug.log

**Comment by arkon** [comment]
Seems like an issue with npm: https://github.com/npm/npm/issues/17858
