### ISSUE TITLE
Sidebar not showing

### ISSUE THREAD

**Issue by sam12c** [arkon/ng-sidebar#128]
Hello,

I am trying to implement this sidebar, however after doing a copy paste of the github project, I see nothing except a blank page:
![image](https://user-images.githubusercontent.com/19272651/32520651-fd8c52ce-c410-11e7-98c7-391fc5b83c5e.png)
However if i remove the "Relative" attribute in the debugger, everything is fine! :
![image](https://user-images.githubusercontent.com/19272651/32520679-235dfcd2-c411-11e7-9a30-3ec717e1ad53.png)

Hence, I am trying to turn off this default "relative" position to absolute, but with very little success. I read through the issue here, tried a bunch of things (!important, host: >>>, starting from a simpler project, etc.) but none seemed to work.

I generated the project using angular cli, and I am using Angular 5.0.

Thanks a lot for your help!

**Comment by arkon** [comment]
Does #100 help?

**Comment by sam12c** [comment]
#121 helped me!
`
<ng-sidebar-container style="position: static;"> => this still works for me.`

Thanks a lot for your help. Cool sidebar!
