### ISSUE TITLE
SidebarContainer injection is always undefined with production build.

### ISSUE THREAD

**Issue by LukeArthurs** [arkon/ng-sidebar#130]
Hi,

First off great package and well made angular code that handles its own change detection.

I'm having one issue when building the production version of my app. I followed the structure used in the demo. ng-sidebars inside ng-sidebar-containers, which works in development mode. Using angular-seed btw.

When I do npm run build.prod (which uses JIT compiling, since my code isnt AOT ready yet) the build is successful but when I try to use the application I get the following Error:
**Error: <ng-sidebar> must be inside a <ng-sidebar-container>. See https://github.com/arkon/ng-sidebar#usage for more info.**

This error is thrown as I found in the sidebar.component.ts constructer with (@Optional() private _container: SidebarContainer)

Im assuming that when the typescript is compiled that the parent component isn't injected properly anymore but I'm not sure exactly.

Do you know any solution to this or is this the first time you're seeing it?
"angular/compiler-cli": "^5.0.1",
 "angular/language-service": "^5.0.1",
 "angular/platform-server": "^5.0.1",
"ng-sidebar": "^6.0.4",
"typescript": "^2.6.1",

**Comment by arkon** [comment]
That's a first for me. Do you know what the difference between the dev and prod JIT builds are in your project?

**Comment by LukeArthurs** [comment]
Not yet, I have to disable the uglify and do some checks of where its going wrong. I didnt have much time since Im running into a deadline so I forked a branch a rewrite the _container to and Input field in the sidebar which works but obviously isn't the right way to do it. When I have time, I'll take a look to see if I can spot the difference.
