### ISSUE TITLE
Sidebar width

### ISSUE THREAD

**Issue by PaulCailly** [arkon/ng-sidebar#132]
Referring to Issue #95 

I tried to change the sidebar width without success. 

Something has changed ?

**Comment by arkon** [comment]
No, it still seems to work for me even in Angular 5. What's your template/styles look like?

**Comment by Thainainan03** [comment]
![image](https://user-images.githubusercontent.com/26254784/33467328-54fb6036-d686-11e7-87a2-b52b63c00516.png)

How to change with in ng-sidebar ?

**Comment by arkon** [comment]
Where are you putting the width styles?
