### ISSUE TITLE
ie9

### ISSUE THREAD

**Issue by lenderby** [arkon/ng-sidebar#133]
There are errors with ie9 on the latest version. On your online demo it says 'WeakMap' is undefined. And my local project gives "TypeError: Unable to get property 'add' of undefined or null reference".

Is it worth me trying to find a workaround like a polyfill or do you have an earlier version that might work?

**Comment by arkon** [comment]
I don't directly use WeakMap, so it's probably just Angular dying in IE9. I don't try to support old versions of IE.
