### ISSUE TITLE
Run time exception on adding ng-sidebar module

### ISSUE THREAD

**Issue by jeshcalls** [arkon/ng-sidebar#134]
Hi,
I used ng-sidebar in my project and get the below error,

Uncaught (in promise): TypeError: ctorParameters.map is not a function

I included SidebarModule.forRoot() in imports section of my feature module. Internet shows it is a dependancy issue. While I debug, I thought if you can give pointers as to why this error shows up.

Thanks,

**Comment by arkon** [comment]
What version of Angular and this library are you using?

**Comment by jeshcalls** [comment]
I am using angular version 4.3.1 and using ng-sidebar 6.0.4
