### ISSUE TITLE
Initial state of sidebar doesn't respect autoCollapseWidth / autoCollapseHeight

### ISSUE THREAD

**Issue by gstercken** [arkon/ng-sidebar#136]
When setting `autoCollapseWidth` (or `autoCollapseHeight`) and loading the application in a viewport narrower (or shorter) than the provided value, the initial state of the sidebar will still be visible if `opened` is bound to a true variable. 

Expected behavior: We are using ng-sidebar in a responsive scenario (sidebar initially visible on wider viewports, and hidden on narrower viewports / mobile, where it can be expanded via a hamburger menu button). Currently, this behavior cannot be achieved without programmatically querying the viewport size and initializing the `opened` value accordingly.

Suggested fix: A very simple fix would be to call `_onResize()` once at the end of `ngOnInit()` (that's how we worked around it locally, and it works).

A cleaner solution would be to move the code from `_onResize()` into a separate method, e.g.  `_updateAutoCollapse()` and call it from both `_onResize()` and `ngOnInit()`.

Additional consideration: Some users might find scenarios where the current behavior (the initial state of `opened` overrides the autoCollapse setting) is desirable, so you might consider making it optional/configurable. Either via:

- An additional input flag (e.g. 'initialAutoCollapse'), or
- make `opened` a tri-state instead of a boolean, so it can be `true`, `false` or `automatic`.

**Comment by AdamKernig** [comment]
+ 1, very handy feature, consider sites like bitbucket who implement this type of feature.
