### ISSUE TITLE
Animation End Event

### ISSUE THREAD

**Issue by tifcohen** [arkon/ng-sidebar#137]
Feature request:
Animation end event.

I need to know when the animation has ended, since I need to resize a complex component and it doesn't work properly because of the animation. If I try it with timeout (after the animation has finished) it's working great.

Thanks!

**Comment by shayts** [comment]
It could be a very help full feature.

**Comment by arkon** [comment]
I don't really think this is necessary since there's `onOpenStart`/`onOpened` (and similarly for closing) which are emitted around the animation.

Regardless, I'll add an output for the `transitionend` event.

**Comment by tifcohen** [comment]
@arkon Thanks!
