### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by MusayevKamran** [arkon/ng-sidebar#139]
I do every steps but it is not working on my project and do not give any error. An show toggle method is not used

**Comment by arkon** [comment]
I'm not sure how you expect me to know what's wrong.

- What does your template look like?
- What version are you using?
- What version of Angular are you using?
- Are there any warnings in the console?
- Do you see any sidebar elements being added to the DOM in the element inspector?

**Comment by MusayevKamran** [comment]
There is not any error but it is not shows in web page


![ngsidebar](https://user-images.githubusercontent.com/17671445/36138790-5d282dd0-10b4-11e8-9fb3-a74c517893f0.png)

**Comment by MusayevKamran** [comment]
I am using latest version angular

**Comment by MusayevKamran** [comment]
Failed: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng-sidebar'.
1. If 'opened' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  
  <ng-sidebar [ERROR ->][(opened)]="_opened">
    <p>Sidebar contents</p>
  </ng-sidebar>
"): ng:///DynamicTestModule/AppComponent.html@4:14
'ng-sidebar' is not a known element:
1. If 'ng-sidebar' is an Angular component, then verify that it is part of this module.
2. If 'ng-sidebar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

  
  [ERROR ->]<ng-sidebar [(opened)]="_opened">
    <p>Sidebar contents</p>
  </ng-sidebar>
"): ng:///DynamicTestModule/AppComponent.html@4:2
'ng-sidebar-container' is not a known element:
1. If 'ng-sidebar-container' is an Angular component, then verify that it is part of this module.
2. If 'ng-sidebar-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
[ERROR ->]<ng-sidebar-container>

  
"): ng:///DynamicTestModule/AppComponent.html@1:0

**Comment by arkon** [comment]
Does #100 help?

**Comment by MusayevKamran** [comment]
```
Failed: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng-sidebar'.
1. If 'opened' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  <!-- A sidebar -->
  <ng-sidebar [ERROR ->][(opened)]="_opened">
    <p>Sidebar contents</p>
  </ng-sidebar>
"): ng:///DynamicTestModule/AppComponent.html@4:14
'ng-sidebar' is not a known element:
1. If 'ng-sidebar' is an Angular component, then verify that it is part of this module.
2. If 'ng-sidebar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

  <!-- A sidebar -->
  [ERROR ->]<ng-sidebar [(opened)]="_opened">
    <p>Sidebar contents</p>
  </ng-sidebar>
"): ng:///DynamicTestModule/AppComponent.html@4:2
'ng-sidebar-container' is not a known element:
1. If 'ng-sidebar-container' is an Angular component, then verify that it is part of this module.
2. If 'ng-sidebar-container' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
[ERROR ->]<ng-sidebar-container>

  <!-- A sidebar -->
"): ng:///DynamicTestModule/AppComponent.html@1:0``
```

**Comment by arkon** [comment]
Are you using SystemJS?

**Comment by MusayevKamran** [comment]
no I use webpack as a default of angular

**Comment by arkon** [comment]
How did you add the sidebar module to your app (I.e. how is it imported in your module (s))?

**Comment by MusayevKamran** [comment]
I followed construction. only `var map = {
  // ...
  'ng-sidebar': 'node_modules/ng-sidebar',
  // ...
};

var packages = {
  // ...
  'ng-sidebar': {
    main: 'lib/index',
    defaultExtension: 'js'
  },
  // ...
};`
this step do nnot added

**Comment by MusayevKamran** [comment]
exsept this I followed construction. I putt foto on top
`var map = {
  // ...
  'ng-sidebar': 'node_modules/ng-sidebar',
  // ...
};

var packages = {
  // ...
  'ng-sidebar': {
    main: 'lib/index',
    defaultExtension: 'js'
  },
  // ...
};`
```

**Comment by MusayevKamran** [comment]
exsept this I followed construction. I putt foto on top
```
`var map = {
// ...
'ng-sidebar': 'node_modules/ng-sidebar',
// ...
};

var packages = {
// ...
'ng-sidebar': {
main: 'lib/index',
defaultExtension: 'js'
},
// ...
};
```

**Comment by arkon** [comment]
Considering the DOM looks fine, this just sounds like an issue with. Angular. You could try deleting `node_modules` and reinstalling them, but otherwise I don't have anything to suggest.

**Comment by MusayevKamran** [comment]
I delete all node_modules and reinstalled but nothig is changed. (( Should I do anything else ?

**Comment by arkon** [comment]
Sorry, I don't know what's wrong.

**Comment by arkon** [comment]
#135 might help

**Comment by MusayevKamran** [comment]
Maybe it is not working on angular 5 ? Is it possible?

**Comment by MusayevKamran** [comment]
I run following command

**Comment by MusayevKamran** [comment]
I run following command for updating package.json
```
$ npm install -g npm-check-updates
$ ncu -u
$ npm install 
```

after updating it worked. Thanks for helping

**Comment by MusayevKamran** [comment]
I thin I found problem firstfull i updated package json 
and then give height and it showed the button. then it worked

<ng-sidebar-container style="height: 100vh;">

  <ng-sidebar [(opened)]="_opened" position="right">
    <ul>
      <li>Menu Item</li>
      <li>Menu Item</li>
      <li>Menu Item</li>
    </ul>
  </ng-sidebar>

  <div ng-sidebar-content>
    <button (click)="_toggleSidebar()">Toggle sidebar</button>
  </div>

</ng-sidebar-container>

**Comment by arkon** [comment]
That's what #100 said. It's also in the README.

**Comment by timaxapa** [comment]
Any other solution without using ```height: 100vh```?

**Comment by mohammadsadeqsirjani** [comment]
dfhyfgh

**Comment by mohammadsadeqsirjani** [comment]
Fuck you allllllllll ♥♥♥♥♥
