### ISSUE TITLE
Add option to push page content

### ISSUE THREAD

**Issue by amccubbin** [arkon/ng-sidebar#14]
It would be helpful to add the ability to select whether the sidebar overlays content or pushes it right|down|left|up depending on location i.e. change the z-index and other styles. 

Example: http://semantic-ui.com/modules/sidebar.html

Or: https://github.com/angular/material2/tree/master/src/lib/sidenav

**Comment by arkon** [comment]
I was considering this since [react-sidebar](https://github.com/balloob/react-sidebar) also somewhat does that, but I didn't get around to it. I supposed I'd need to add a container component for the page contents so that they can be coordinated as well.

I think I'll eventually add this, but I'm not sure how soon.

**Comment by priesett** [comment]
Adding my two cents, push and docked would be great. I'm looking to use this, but want to give users the option to pin it.

**Comment by arkon** [comment]
I'll likely be working on this over the Christmas holidays. :)

**Comment by Akahadaka** [comment]
I would like to use this suggested feature in a project too. As well as a docked version where I can control the the translation of how far the sidebar disappears. I.e. Icons still visible to click on without opening the full sidebar and its longer descriptions.

**Comment by arkon** [comment]
@Akahadaka I've logged the second part of your comment in #30.

**Comment by arkon** [comment]
Done in the master branch. Will be released later as part of v3.0.0.

**Comment by arkon** [comment]
v3.0.0 has been released on NPM. Check out [the changelog](https://github.com/arkon/ng-sidebar/releases/tag/v3.0.0) for more info.
