### ISSUE TITLE
keyClose doesn't work with input fields inside the sidebar

### ISSUE THREAD

**Issue by klsdfr** [arkon/ng-sidebar#142]
I have some input-fields in the sidebar and when a key is pressed, when one of them is focused, the sidebar is closing even though keyClose is set to false.
I already tried to change trapfocus and autofocus to true and false, but the problem still exists.

Does anyone else gets this issue?

**Comment by arkon** [comment]
How are you setting `keyClose` to false? This doesn't happen when I try it.
