### ISSUE TITLE
Angular 4 Support

### ISSUE THREAD

**Issue by mfish0005** [arkon/ng-sidebar#143]
In the most recent [changelog](https://github.com/arkon/ng-sidebar/releases) it mentions Angular 5 as a dependency.  Does this mean ng-sidebar will no longer work with versions prior to 5?

I'm using Angular 4 and can't seem to get it working with the example even after referencing [#100](https://github.com/arkon/ng-sidebar/issues/100)

**Comment by arkon** [comment]
What's the error you're getting (if any)? npm should complain if you're installing something where the peer deps don't match up.

**Comment by arkon** [comment]
But yes, you'd need to use something below v7.0.0 if you're using Angular 4.

**Comment by mfish0005** [comment]
I updated my project to Angular 5 and it works great now.  Thanks for this it saves me a ton of work!

**Comment by mfish0005** [comment]
Just in case someone else has a similar problem this was the npm warning:
 `UNMET PEER DEPENDENCY +-- angular@5.0.x +`
Or something along those lines

**Comment by vgogov** [comment]
Also the case if you get something similar when building the project:

> ERROR in Metadata version mismatch for module /home/user/blabla/node_modules/ng-sidebar/lib/index.d.ts, found version 4, expected 3.

If you are using anything Angular 4, just install version 6.0.5 of ng-sidebar :)
