### ISSUE TITLE
Does not work when sidebar is encapsulated in another component

### ISSUE THREAD

**Issue by shoaib-xo** [arkon/ng-sidebar#145]
See demo 

https://test-sidebar.stackblitz.io
https://stackblitz.com/edit/test-sidebar

The "Sidebar opening" events are logged but nothing after that. Putting the <sidebar> as direct child of the container works, but it really limits the encapsulation and re-usability.

**Comment by KlemensE** [comment]
The reason might be this [line](https://github.com/arkon/ng-sidebar/blob/master/src/sidebar-container.component.ts#L27). 

It could be extended to allow any element with a specific attribute.

**Comment by arkon** [comment]
That could be it. Anyone want to try it and submit a PR?

**Comment by arkon** [comment]
Published v7.2.0.

**Comment by alleey** [comment]
That was quick!
