### ISSUE TITLE
Nested sidebars with varying lengths

### ISSUE THREAD

**Issue by geoffhuntoon** [arkon/ng-sidebar#147]
Is it possible to have nested sidebars, with the inner sidebar being longer than the outer sidebar? 

Use case: I'm searching with a form, and the outer sidebar has search results that appear alongside the form. Then, when clicking on a result, the inner sidebar opens with more details about that result, ideally taking up the whole page. As of now, my inner sidebar does take up the whole page but it slides over the search results and under the search form.

Do I need two ng-sidebar-containers? It seems like both are responding fine to my outer ng-sidebar-container, but I'm not sure.

**Comment by arkon** [comment]
I've honestly never thought about that sort of use case, nor do I know the answer off the top of my head. You might be able to do it with some style trickery.
