### ISSUE TITLE
sidebar does not remove click listener if changed during sidebar is open

### ISSUE THREAD

**Issue by cluetjen** [arkon/ng-sidebar#148]
We're using the sidebar with three states:

* docked
* over with closeOnClickOutside=true
* push with closeOnClickOutside=false

If sidebar is open (over), users can click an icon to switch to "open and stay open" mode (push):

* mode=over, closeOnClickOutside=true
* User clicks "stay open"
* mode=push, closeOnClickOutside=false

Problem:

Sidebar does not remove click listeners for closeOnClickOutside and sidebar will continue to close when user clicks somewhere. 

I think it's because sidebar.ngOnChanges does not cover closeOnClickOutside=false > remove existing listeners and in all other situations the listeners are removed only if sidbar is closed.

**Comment by arkon** [comment]
#149
