### ISSUE TITLE
[QUESTION] Scrollto behavior

### ISSUE THREAD

**Issue by vogloblinsky** [arkon/ng-sidebar#150]
Hi,

Thanks for this good angular library.

Is it possible to have this behavior : 
- links in sidebar that are just links to anchors in main content area. When a user click on it, the sidebar close, and the content area scrollto the corresponding anchor.

Thanks

**Comment by arkon** [comment]
Seems out of scope, but you can programmatically close the sidebar. Your click handler for the links should close the sidebar then scroll your page.

**Comment by vogloblinsky** [comment]
Ok no problem.
