### ISSUE TITLE
Change position at runtime

### ISSUE THREAD

**Issue by Msender** [arkon/ng-sidebar#152]
I try to change the position at run-time form right to top, but the new position is only applied for the next time I open the sidebar, it looks like it takes a while till the new position gets applied, how can I apply the new position that it should take affect immediately?

Thanks

**Comment by arkon** [comment]
That's kind of weird, it works fine in the demo. How are you doing it?

**Comment by Msender** [comment]
In the demo you change the position, but you don't open it at the same time, if you do both at the same time it doesn't take affect right away, see this sample [https://stackblitz.com/edit/angular-sfs7yp](url)

**Comment by arkon** [comment]
> also in the sample when position top it does not animate when close.

It does, it's just a bit awkward and hard to see.
