### ISSUE TITLE
remove scroll bar in content portion

### ISSUE THREAD

**Issue by jeshcalls** [arkon/ng-sidebar#156]
Hi,

I am using ng side bar and setup height=100vh for displaying the content in angular v6. But what happens when my content is more than the viewport a scroll bar appears along with browser scroll bar. 

I want to use the browser scrollbar only for this purpose. 

Tried some hack of updating height based on the size of the form. But doesnt look clean. Have someone faced this issue and solved it perfectly.

Thanks,

**Comment by arkon** [comment]
You probably have extra margin in some element.
