### ISSUE TITLE
Add option to make header content overlaps sidebar

### ISSUE THREAD

**Issue by andreyjkee** [arkon/ng-sidebar#159]
Hi @arkon. Thank you for your great work on this component.
Can you add optional ability to make the header that overlaps sidebar, like in my screenshot:
![image](https://user-images.githubusercontent.com/506555/45611930-eae4dd80-ba69-11e8-8de1-22692ebb13a3.png)
Or if some workaround exists can you help with it?
For example here https://stackblitz.com/angular/mggrmqgvbqn?file=app%2Fsidenav-fixed-example.ts I can add top/bottom gap for sticky header/footer

**Comment by arkon** [comment]
That's out of scope of this package, but the source code [is available in this repo](https://github.com/arkon/ng-sidebar/tree/master/demo) for that demo, which just relies on basic styling.
