### ISSUE TITLE
Angular V6 - Page not loading at all

### ISSUE THREAD

**Issue by jamshed-qureshi-mobinext** [arkon/ng-sidebar#161]
I'm having the same issue as #100 and I've also applied '<ng-sidebar-container style="height: 100vh;">'. Also I've applied "position:static;" property. My page gets loaded in the browser but it doesn't render at all.

Point to mention here is that I'm using the ng-sidebar-container directive in a nested module's component, however I've also imported the SidebarModule in the nested module's import array. Is the problem because I've used SidebarModule.forRoot() in the nested module or is it something else.

This page's component is not app.component instead it's in a routed component.

**Comment by jamshed-qureshi-mobinext** [comment]
I've applied height:100vh property to ng-sidebar-container but that didn't help.

**Comment by arkon** [comment]
Is there actually an error or is the content not just displaying?

**Comment by arkon** [comment]
Is there actually an error or is the content not just displaying?

**Comment by jamshed-qureshi-mobinext** [comment]
There is no error, but the page content is not getting displayed at all. I gave height:100vh; to all the parent directives(i.e router-outlet) of the route as well but it didn't help much. I think the problem lies in using "SidebarModule.forRoot()" in the nested module. Correct me if I'm wrong.

**Comment by arkon** [comment]
If you inspect the page, is the content actually in the container component?

**Comment by arkon** [comment]
You can dropping the `forRoot()` part too if you think that's the issue. I don't have much experience with nested modules though.

**Comment by jamshed-qureshi-mobinext** [comment]
I dropped the forRoot() part, still it didn't help either.
