### ISSUE TITLE
How can i bind the "dock" @input to a function (2 way)

### ISSUE THREAD

**Issue by pilouk** [arkon/ng-sidebar#162]
I'm quite new to angular 2+ and i'm wondering how can i two way the "dock" input with a function ?
Is this possible?
Thanks!

**Comment by arkon** [comment]
What's the usecase here? The `dock` value wouldn't be changing from inside the component, so I'm not sure why you would want it to be two-way bound.

**Comment by pilouk** [comment]
Ur right It don't need 2 ways
