### ISSUE TITLE
Running Demo

### ISSUE THREAD

**Issue by tihomirmagdic** [arkon/ng-sidebar#163]
Hi,
There is no angular.json to run demo separately.
I can run demo only thru npm build and then open built index.html. Is it possible to run demo with ng serve, and to reload demo whenever I change library in the parent directory?

Tihomir

**Comment by tihomirmagdic** [comment]
Meanwhile I found that everything works just fine with npm start

**Comment by tihomirmagdic** [comment]
How to setup dev env where changing library in the parent directory causes automatic demo reloading?

**Comment by arkon** [comment]
This was created way before Angular CLI existed.

You could `npm link` it but I don't really work on it often enough that to bother really improving the dev environment.
