### ISSUE TITLE
Dock padding stay there even if ng-sidebar *ngIf has been triggered to false

### ISSUE THREAD

**Issue by pilouk** [arkon/ng-sidebar#165]
First, we use the sidebar with dock with a docked size of 50px. We also have a login screen which we don't want the sidebar to appear useless the user is logged in.
Everything works fine for the first load but when the sidebar ngIf change from "true" to "false" for example when the user "log out " the side bar does disappear but the docked size padding remain and create an offset on the container which should not be here.

**Comment by arkon** [comment]
The container itself handles that logic along with the sidebar. You might be able to "hide" it by changing the the mode and open states instead.

**Comment by pilouk** [comment]
I think dock / mode is not two way binding , not sure if i could change it straight away to "hide" it.

**Comment by arkon** [comment]
Sorry, I actually meant the `dock` input instead of mode. You should be able to just set `[dock]` to false if you don't want to show it.

There's no need for two way binding here. Are you used to two way binding from Angular.js, maybe?

**Comment by pilouk** [comment]
> Sorry, I actually meant the `dock` input instead of mode. You should be able to just set `[dock]` to false if you don't want to show it.
> 
> There's no need for two way binding here. Are you used to two way binding from Angular.js, maybe?

Sorry i thought that two way was necessary to pick up change on the fly instead of setting it once.

**Comment by pilouk** [comment]
> Sorry, I actually meant the `dock` input instead of mode. You should be able to just set `[dock]` to false if you don't want to show it.
> 
> There's no need for two way binding here. Are you used to two way binding from Angular.js, maybe?

I'm probably wrong but i would like that [dock] pick up change from a property instead of modifying a variable. For example 

`  get isDocked(): boolean {
    return  !this.isMobile && this.authService.isLoggedIn;
}`

In my html it would look like 
`[dock]="isDocked"`

Can your component could detect change from my property ? or i need to do an observable which watch loggedin status and modify a specific variable

Thanks!

**Comment by pilouk** [comment]
I did try with subscribing my login status event which trigger when log in and logout and successfully changing the [dock] but the padding remain there.

**Comment by pilouk** [comment]
I may know why ... The ngIf destroy the component so is this normal that dock doesn't respond... i will try with hidden

**Comment by pilouk** [comment]
Yep i had to use Hidden instead of ngIf which make sense after all.
