### ISSUE TITLE
Demo does not work on Stackblitz

### ISSUE THREAD

**Issue by pappasa** [arkon/ng-sidebar#167]
Could you please make the demo work on Stackblitz? Loading https://stackblitz.com/github/arkon/ng-sidebar/tree/master/demo gives the error:

This project type is not yet supported.
We currently only support projects scaffolded with @angular/cli.
If you think this is a bug, please file an issue in our repo!

**Comment by arkon** [comment]
I don't intend on refactoring to use the CLI. I'd be happy to review PRs though.

**Comment by pappasa** [comment]
I created the project [ng_sidebar_demo on Stackblitz](https://stackblitz.com/edit/ng-sidebar-demo) but I cannot make it work. Do you have an idea, what could be wrong?

**Comment by arkon** [comment]
It's not actually [importing the styles](https://github.com/arkon/ng-sidebar/blob/3e2817ad90cb5660b64b1439f51c11289534457c/demo/src/bootstrap.ts#L8).

**Comment by pappasa** [comment]
I have imported the styles in main.ts:

```
import { NgModule, enableProdMode } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { SidebarModule } from 'ng-sidebar';

import { DemoComponent } from './demo/demo.component';

import './styles/styles.scss';

// enableProdMode();

@NgModule({
  declarations: [DemoComponent],
  imports: [BrowserModule, SidebarModule.forRoot()],
  bootstrap: [DemoComponent],
})
class DemoAppModule {}

platformBrowserDynamic().bootstrapModule(DemoAppModule);
```

**Comment by arkon** [comment]
It's not actually working though, the styles aren't actually taking effect.

**Comment by pappasa** [comment]
I replaced styles.scss with src/styles.css and src/demo.component.css and now [ng_sidebar_demo on Stackblitz](https://stackblitz.com/edit/ng-sidebar-demo) works.

**Comment by arkon** [comment]
Awesome. 👍
