### ISSUE TITLE
Bootstrap modal isn't pushed to the right when ng-sidebar is opened

### ISSUE THREAD

**Issue by vgabv** [arkon/ng-sidebar#169]
Hi, I would like to have my modal pushed to the right when my right-positioned sidebar is opened, but i couldn't find a solid solution... Why isn't it being pushed automatically?

**Comment by arkon** [comment]
Probably because the modal is at a fixed position. There isn't much this library can do about it since that's a pretty specific use case, unfortunately.

**Comment by vgabv** [comment]
@arkon I see, thanks for the answer. Do you have any advice to at least not allow the sidebar to cover the modal?

**Comment by arkon** [comment]
You might be able to post around with the `z-index` of the sidebar component via CSS.

**Comment by vgabv** [comment]
@arkon thanks! love the component btw
