### ISSUE TITLE
/deep/ combinator is no longer supported in Angular 7

### ISSUE THREAD

**Issue by DevTahsin** [arkon/ng-sidebar#171]
Current packages on App:

- "ng-sidebar": "8.0.0",
- "@angular/common": "7.1.0",
- "@angular/compiler": "7.1.0",
- "@angular/core": "7.1.0",
- "@angular-devkit/core": "7.0.6"

Chrome says:
> sidebar.component.js:469 [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

Proposed solution was "::ng-deep" at:
[deprecated-deep--and-ng-deep](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep)

**Comment by arkon** [comment]
The component doesn't actually use `/deep/`. Are you using it in your app?

**Comment by DevTahsin** [comment]
My fault, sory about that...  but on product why chrome says that message from side sidebar.component.js:469
