### ISSUE TITLE
Bootstrap components

### ISSUE THREAD

**Issue by Code202** [arkon/ng-sidebar#177]
Hi, I have downloaded the module and  it's just awesome.

Well I have been in a little trouble with bootstrap, indeed when I try to use some bootstrap component inside sidebar content area, the height of sidebar is equal to the height of whole bootstrap components inside and not the height of the screen.

I hope I have well explained my issue.

**Comment by arkon** [comment]
I don't have enough info to help, unfortunately. You can probably try to debug it by looking at the elements' style properties in dev tools.
