### ISSUE TITLE
There is an approach to open sidebar in sidebar option?

### ISSUE THREAD

**Issue by habundes** [arkon/ng-sidebar#178]

**Comment by arkon** [comment]
I'm not sure I understand. You want a sidebar inside a sidebar?

**Comment by habundes** [comment]
yes, i meant that like nested side bar clicking an option inside main sidebar like this:

        Main Sidebar
----------------------------------|              Second Sidebar
                                                  |--------------------------------|
                                                  |                                               |
                                                  |                                               |
   Menu option link                   |                                               |
                                                  |                                               |
                                                  |                                               | 
                                                  |                                               |
                                                  |                                               |

**Comment by arkon** [comment]
I feel like that got parsed really badly by Markdown, but you want a regular sidebar on the left, and when you click something inside, a second sidebar slides out to the right of it?

You can in theory have multiple `<ng-sidebar>`s within an `<ng-sidebar-container>`, which are each controlled with their own `[(opened)]` values. You can also control sidebars from other places within your application via some Angular services. So, _in theory_, your menu option in one sidebar can trigger another sidebar.

You could apply some styles to the second sidebar such that it appears beside the first one.
