### ISSUE TITLE
Ivy render issue

### ISSUE THREAD

**Issue by webcat12345** [arkon/ng-sidebar#184]
With new angular 8 and ivy renderer, we are having this problem.

https://github.com/angular/angular/issues/29564#issuecomment-496766923

**Comment by pl4yradam** [comment]
+ 1 im getting the same

**Comment by arkon** [comment]
Does this happen with the stable release? I haven't been keeping up with Angular much (re: at all).

**Comment by webcat12345** [comment]
Sorry @arkon not stable release yet. maybe with 9.

**Comment by arkon** [comment]
Supposedly fixed with Angular 8.2.0-next.0

https://github.com/angular/angular/issues/29564
