### ISSUE TITLE
sidebar should not cover the other elements (z-index) in push and slide mode 

### ISSUE THREAD

**Issue by RezaRahmati** [arkon/ng-sidebar#186]
### Steps to Reproduce:

1. Open this [https://codesandbox.io/s/filtering-devextreme-data-grid-6zs9y?fontsize=14](https://codesandbox.io/s/filtering-devextreme-data-grid-6zs9y?fontsize=14)
2. click on "Invoice Number" header filter icon

### Results You Received:
filter panels opens in wrong position

![image](https://user-images.githubusercontent.com/10086092/60909899-5f814680-a24d-11e9-97be-e10e4d89e15d.png)

### Results You Expected:
filter panel opens in correct position

### Note:
I solved the issue in my app by adding these to styles

```
::ng-deep .ng-sidebar.ng-sidebar--opened.ng-sidebar--push,
::ng-deep .ng-sidebar.ng-sidebar--opened.ng-sidebar--slide {
  z-index: 1;
}

```

**Comment by RezaRahmati** [comment]
I am not sure if that changes is correct, because it was correct if the mode was "over", so that changes only needed for push and slide

**Comment by arkon** [comment]
There's basically no winning since I'll never know what the sites that are using the component are like.

Regardless, users are free to override the `z-index` like the workaround you provided as well.

**Comment by RezaRahmati** [comment]
@arkon I tried to create a branch and do pull request but I got access denied. I would suggest the below code

```
    .ng-sidebar {
      -webkit-overflow-scrolling: touch;
      overflow: auto;
      pointer-events: auto;
      position: absolute;
      touch-action: auto;
      will-change: initial;
      z-index: 1;
    }

    .ng-sidebar.ng-sidebar--over {
      z-index: 99999999;
    }
```
