### ISSUE TITLE
Runtime error with Ivy

### ISSUE THREAD

**Issue by kKen94** [arkon/ng-sidebar#187]
![image](https://user-images.githubusercontent.com/46461611/62279299-18503500-b44a-11e9-9d5a-12a8eaeab32c.png)

and this is the sidebar-container.component.js

![image](https://user-images.githubusercontent.com/46461611/62279479-7aa93580-b44a-11e9-93df-8bd245fe1bd7.png)

I don't know what else to say, just post the screens

**Comment by tonymarkoc** [comment]
I'm experiencing this problem as well. Had to turn off ivy in order to run the application.

**Comment by kKen94** [comment]
Sure, but I would like to use Ivy

**Comment by nicorivat** [comment]
I'm facing the same issue.
To fix this just need to add "decoratorsAs": "static fields" in your angularCompilerOptions (tsconfig.json) and rebuild your library ;)
(on the ng-sidebar side of course)

**Comment by arkon** [comment]
PRs are welcome. :)

**Comment by kKen94** [comment]
Angular 9 will be available in few days. It would be a shame to have to give up this library if build with Ivy will not fix

**Comment by kKen94** [comment]
Still not work

![image](https://user-images.githubusercontent.com/46461611/70048270-2b2a7000-15ca-11ea-95d1-cce6ee95766d.png)

**Comment by kKen94** [comment]
I'm doing some tests. If I enable Ivy on Angular 8 this lib doesn't work. But with Angular 9 rc4 it works

**Comment by darpit** [comment]
Hi @arkon ,

I am getting below error with Angular 9.1 (Ivy enabled).

### Below Error with forRoot().

```

>     ERROR in node_modules/ng-sidebar/lib/sidebar.module.d.ts:3:23 - error NG6005: SidebarModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type 
> argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, 
> please contact the library authors.
>     
>     3     static forRoot(): ModuleWithProviders;
>                             ~~~~~~~~~~~~~~~~~~~
>     src/app/layout/layout.module.ts:21:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
>     

```
### Below Error Without forRoot()
> `This likely means that the library (ng-sidebar) which declares SidebarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

**Comment by ruchitp** [comment]
> Hi @arkon ,
> 
> I am getting below error with Angular 9.1 (Ivy enabled).
> 
> ### Below Error with forRoot().
> ```
> 
> >     ERROR in node_modules/ng-sidebar/lib/sidebar.module.d.ts:3:23 - error NG6005: SidebarModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type 
> > argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, 
> > please contact the library authors.
> >     
> >     3     static forRoot(): ModuleWithProviders;
> >                             ~~~~~~~~~~~~~~~~~~~
> >     src/app/layout/layout.module.ts:21:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> >     
> ```
> 
> ### Below Error Without forRoot()
> > `This likely means that the library (ng-sidebar) which declares SidebarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

I am also getting same error.
@arkon Any solution for this? This functionality is very important for us. Any quick solution is appreciated.
Thanks in advance.

**Comment by arunwebber** [comment]
I am also experiancing same problem any update is really appriciatable.
