### ISSUE TITLE
Backdrop doesn't cover nested sidebar

### ISSUE THREAD

**Issue by napowelson** [arkon/ng-sidebar#194]
In my application I have a main sidebar for the "main menu", and a drawer in a sub-module.  When the drawer is visible, and the menu is opened, the backdrop doesn't cover the nested.

Here is a quick demo: https://stackblitz.com/edit/angular-ng-sidebar-rmsa6l

Is there a way to fix this with CSS?  I can't seem to be able to target the backdrop.
If not with CSS, is there another way to fix it?

**Comment by arkon** [comment]
I think you should be able to pass in classes to the backdrop and sidebars and set their `z-index` values manually.

**Comment by napowelson** [comment]
The way I was able to fix it was with the following code in the angular feature module:
`:host ::ng-deep .ng-sidebar{
  z-index: inherit;
}`
