### ISSUE TITLE
Open sidebar from another component.

### ISSUE THREAD

**Issue by elanioazul** [arkon/ng-sidebar#198]
Hi, Im struggling trying to make this work:

a button in a footer component triggering the open function to open the sidebar (which is another component which I want to see being slide over the main component in my webapp, a map). So 3 components here: footer with open botton, sidebar and a map.
I could go with map inside the Page content section (ng-sidebar-content) of the sidebar component, but definitelly open botton belongs to another component.

How to make use of this open() function from another component, my footer?
Is there a way to pass the ng-sidebar functionality to another component?

**Comment by partharanjan** [comment]
You can use subscription(Subject) to do all communication.
