### ISSUE TITLE
Can't nest components inside ng-sidebar

### ISSUE THREAD

**Issue by Gabriel-gn** [arkon/ng-sidebar#199]
Is it possible to put components inside ng-sidebar-content?
I've been trying without success...

ng-sidebar seems to seems to always push content of app-content.
Below my code.

```
<ng-sidebar #sidebar >
    <div ng-sidebar-content>
       <app-content></app-content>
    </div>
</ng-sidebar-container>
```

**Comment by arkon** [comment]
Are you sure your code is right? It seems to be missing the opening tag for the container and the closing tag for the sidebar.

**Comment by Gabriel-gn** [comment]
Sorry, my code is a bit messy. Below it more readable:

```
<app-navbar></app-navbar>
<ng-sidebar-container style="height: 100vh; display: inline;">

    <ng-sidebar #sidebar 
    [opened]="sidebarOpened" 
    [dock]="true" 
    [dockedSize]="'40px'" 
    [mode]="'push'"
    [position]="'left'"
    [closeOnClickOutside]="false">
    <!-- Sidebar content  -->
   </ng-sidebar>

   <div ng-sidebar-content>
      <app-content></app-content>
    </div>
  
</ng-sidebar-container>
```

**Comment by arkon** [comment]
It's hard to tell without actually being to see the site. Your best bet would be poking around in dev tools to see why it's pushing things.

**Comment by Gabriel-gn** [comment]
Thanks. I'll try to debug it, it's probably not a problem with the module
