### ISSUE TITLE
Version 9.4.0 Seems Mispublished on NPM?

### ISSUE THREAD

**Issue by patrick-entinux** [arkon/ng-sidebar#207]
I get the following error during `ng build` or `ng serve`:

```
ERROR in apps/web-app/src/app/app.module.ts:11:31 - error TS2307: Cannot find module 'ng-sidebar'.

11 import { SidebarModule } from 'ng-sidebar';
```

Upon inspection it seems there is only the src folder in my node_modules/ng-sidebar:

![image](https://user-images.githubusercontent.com/37786000/85665697-95396c80-b6f6-11ea-9b83-2bacf314b762.png)

Seems to be the same when I browse on unpkg too:

https://unpkg.com/browse/ng-sidebar@9.4.0/

**Comment by arkon** [comment]
Whoops, my bad! Should be fixed by 9.4.1.
