### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by Et3rnal** [arkon/ng-sidebar#225]
I'm on 9.1.1 I have updated my angular project to v10 from v8, while the ng-sidebar seems to work fine I don't see any changelogs to the newer versions.
Are there any improvements? breaking changes? support for new angular?

**Comment by arkon** [comment]
I've updated https://github.com/arkon/ng-sidebar/releases

You can also refer to the [commit history](https://github.com/arkon/ng-sidebar/commits/master) for more details.
