### ISSUE TITLE
Sidebar does not hide on iOS 8

### ISSUE THREAD

**Issue by JirkaChadima** [arkon/ng-sidebar#28]
First of all, animations don't work well on older mobile devices, we can live with that (and that's not the real issue). But if we turn them off, sidebar does not get hidden on old iOS. It seems to be an issue with a non-prefixed transform (see http://stackoverflow.com/questions/30128587/ios-safari-transition-transform-not-working).

**Comment by arkon** [comment]
@JirkaChadima I wasn't prioritizing older browsers when I was working on this, but I'd welcome a PR for these fixes. Otherwise, I'll eventually get around to it.

**Comment by JirkaChadima** [comment]
Thanks, it's ok. We will probably need some kind of animation anyway, so we
might develop another solution for this.

If I find some time in coming weeks, I'll try to push a PR

**Comment by arkon** [comment]
@JirkaChadima Are you using the [web-animations polyfill](https://github.com/web-animations/web-animations-js)? I think it's supposed to bring proper support (including vendor prefixes) to older browsers.

**Comment by JirkaChadima** [comment]
Yeah, we are, but it was actually probably an issue in our webpack config.
We had no prefixes set in less-loader.

S pozdravem
Jiří Chadima

**Comment by arkon** [comment]
It might be worth checking out @Sifawm's fork that uses regular CSS stuff to do it instead: https://github.com/Sifawm/ng2-sidebar-css3

**Comment by arkon** [comment]
Should be fixed in upcoming v3.0.0.
