### ISSUE TITLE
Feature request: SidebarService

### ISSUE THREAD

**Issue by Sifawm** [arkon/ng-sidebar#29]
If you write a element with the closeSidebar directive directly on the lightdom of the ng2-sidebar all runs as expected.

```typescript
@Component({
  selector: 'my-app',
  styles: [":host /deep/ ng2-sidebar aside { background-color: white }"],
  template: `
    <ng2-sidebar [(open)]="_open">
      <p>Sidebar contents</p>
      <a closeSidebar>Close</a>
    </ng2-sidebar>

    <button (click)="_toggleSidebar()">Toggle sidebar</button>
  `
})
export class App {
  private _open: boolean = false;

  private _toggleSidebar() {
    this._open = !this._open;
  }
}
```

But, if you insert and component that includes the closeSidebar directive on the lightdom, the sidebar doesn't close.

```typescript
@Component({
  selector: 'my-app',
  styles: [":host /deep/ ng2-sidebar aside { background-color: white }"],
  template: `
    <ng2-sidebar [(open)]="_open">
      <p>Sidebar contents</p>
      <close-sidebar></close-sidebar>
    </ng2-sidebar>

    <button (click)="_toggleSidebar()">Toggle sidebar</button>
  `
})
export class App {
  private _open: boolean = false;

  private _toggleSidebar() {
    this._open = !this._open;
  }
}

@Component({
  selector: 'close-sidebar',
  template: `
    <a closeSidebar>Close</a>
  `
})
export class CloseSidebar{}
```

I think, and my team use this, ng2-sidebar needs a SidebarService that have a subscriber and the functions to execute this close function. With this, closeSidebar can put on any component inside or outside of the sidebar if it needed.

If you like, we can send a pull request with this feature.

[Plnkr](http://plnkr.co/edit/eyVQKDFeAJUJpH51O9MR)
[Example service on our fork](https://github.com/Sifawm/ng2-sidebar-css3/blob/master/src/sidebar.service.ts)

**Comment by arkon** [comment]
@Sifawm A PR would be greatly appreciated!

**Comment by Sifawm** [comment]
Great! I will prepare the pull request on the next days.

**Comment by arkon** [comment]
v3.0.0 has been released on NPM. Check out [the changelog](https://github.com/arkon/ng-sidebar/releases/tag/v3.0.0) for more info.
