### ISSUE TITLE
Custom collapse amount

### ISSUE THREAD

**Issue by arkon** [arkon/ng-sidebar#30]
As requested in #14, it'd be nice to be able to specify the collapse amount so it's not always 110% (e.g. showing a thin portion when "collapsed").

**Comment by Akahadaka** [comment]
This would be amazing! Thank you!

As a quick note, I did try achieve something like this using CSS alone. But the sidebar becomes inactive when in a closed state, so even when a portion is visible, clicks will propagate through to the main template.

I haven't gone further that that initial test.

**Comment by arkon** [comment]
I might have to revert to using CSS transitions/animations until the ability to dynamically adjust animation states lands (https://github.com/angular/angular/issues/9668). 🤔

**Comment by arkon** [comment]
Will be in the upcoming v3 release.

**Comment by arkon** [comment]
v3.0.0 has been released on NPM. Check out [the changelog](https://github.com/arkon/ng-sidebar/releases/tag/v3.0.0) for more info.
