### ISSUE TITLE
Unable to integrate with a new project created with angular-cli

### ISSUE THREAD

**Issue by techysoul** [arkon/ng-sidebar#33]
**Setup** - 

- OS - macOS Sierra 10.12.2
- Node - v6.9.2
- NPM - v4.0.4
- IDE - IntelliJ Idea CE

I am able to clone, compile and run the demo directly but not able to integrate ng-sidebar with my new angular-cli created project.

I have followed the instructions given in the readme.md file [here](https://github.com/arkon/ng-sidebar
)
If I add just `<ng-sidebar </ng-sidebar>` then it doesn't give any error. However if I add the content from the github readme file 

```
    <!-- Container for sidebar(s) + page content -->
    <ng-sidebar-container>

      <!-- A sidebar -->
      <ng-sidebar [(opened)]="_opened">
        <p>Sidebar contents</p>
      </ng-sidebar>

      <!-- Page content -->
      <button (click)="_toggleSidebar()">Toggle sidebar</button>

    </ng-sidebar-container>
```

then get following error.

Error - 
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng-sidebar'.
1. If 'ng-sidebar' is an Angular component and it has 'opened' input, then verify that it is part of this module.
2. If 'ng-sidebar' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

      <!-- A sidebar -->
      <ng-sidebar [ERROR ->][(opened)]="_opened">
        <p>Sidebar contents</p>
      </ng-sidebar>
"): AppComponent@4:18
'ng-sidebar-container' is not a known element:
1. If 'ng-sidebar-container' is an Angular component, then verify that it is part of this module.
2. If 'ng-sidebar-container' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<!-- Container for sidebar(s) + page content -->
    [ERROR ->]<ng-sidebar-container>

      <!-- A sidebar -->
"): AppComponent@1:4 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {_nativeError: Error: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng-sidebar'…} Error: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng-sidebar'.
1. If 'ng-sidebar' is an Angular component and it has 'opened' input, then verify that it is part of this module.
2. If 'ng-sidebar' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

      <!-- A sidebar -->
      <ng-sidebar [ERROR ->][(opened)]="_opened">
        <p>Sidebar contents</p>
      </ng-sidebar>
"): AppComponent@4:18
'ng-sidebar-container' is not a known element:
1. If 'ng-sidebar-container' is an Angular component, then verify that it is part of this module.
2. If 'ng-sidebar-container' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<!-- Container for sidebar(s) + page content -->
    [ERROR ->]<ng-sidebar-container>
```

**Comment by arkon** [comment]
Sorry, the `master` branch here on GitHub is actually a WIP. I should probably move it to another branch, but try following the instructions as seen on on NPM instead: https://www.npmjs.com/package/ng-sidebar

**Comment by techysoul** [comment]
Hi Arkon,
Many thanks for the prompt response and this awesome work for the community.
Wish you a very happy new year 2017.
Actually I am able to run the demo by cloning with the latest master github repo. 
However NPM version is giving me reported error.
The latest version of Angular-CLI for Angular 2 generates main.ts, app.module.ts and app.component.ts files. SystemJS is replaced by Webpack after beta10. 
So the instructions on the github link become -
1. npm install using --save option to add the dependency in my package.json
2. Add the import into app.module.ts as suggested
3. Add the code to include sidebar in template as per syntax.

Is there anything that I am missing?

If not then should I delete the cloned repo, uninstall ng-sidebar, clean my npm cache and redo this again?

**Comment by arkon** [comment]
If you were following the instructions in the `README.md` file when it contained things like `[(opened)]` or `<ng-sidebar-container>`, then it won't work with the version published on NPM right now.

Try following the instructions as see [here on NPM](https://www.npmjs.com/package/ng-sidebar) instead.

**Comment by techysoul** [comment]
Yes, I am able to follow the instructions and get it working for NPM version.
However I wanted to use the side bar exactly like the way it works on GitHub version.
Looks like I will need to find a way to compile and use your github version locally.
Absolutely no pressure.. but may I know when are you planning to put the ng-sidebar-container version in NPM. 
Thanks again for this really useful plugin!

**Comment by arkon** [comment]
I'm planning on completing the v3 features sometime this week.

**Comment by techysoul** [comment]
Perfect. Thanks.

**Comment by techysoul** [comment]
Workaround to be used until Arkon releases v3.0 - 
1. Clone the Github version and compile using npm install as normal.
2. Assuming you cloned it at the same level of your project, just change the ng-sidebar dependency in package.json from `"ng-sidebar": "^2.0.0",` to `"ng-sidebar": "file:../ng-sidebar/",` and enjoy all the new features now!
Shared here so that just in case somebody else stumbles on the same issue can get it resolved quickly.

**Comment by arkon** [comment]
I can't really say I recommend doing so since the WIP code is very much that -- WIP. It's still incomplete/buggy.

If you do insist on doing so though, make sure you also checkout the v3 branch.

**Comment by arkon** [comment]
v3.0.0 has been released on NPM. Check out [the changelog](https://github.com/arkon/ng-sidebar/releases/tag/v3.0.0) for more info.

**Comment by techysoul** [comment]
Thanks Arkon.
Just want to know if you are planning to add a feature to show the bar only for portion of the screen. Let's say I would like to see the bar only 80% of the screen's height by leaving 10% at the  top and 10% at the bottom. Can this be achieved using CSS with the current version?

**Comment by arkon** [comment]
@techysoul You should be able to do that via CSS with something like:

```CSS
.ng-sidebar--opened.ng-sidebar {
  height: 100%;
  margin-top: 10%;
}
```
