### ISSUE TITLE
user forRoot static method 

### ISSUE THREAD

**Issue by tsm91** [arkon/ng-sidebar#35]
Hi @arkon, i cant use this module in my shared module because of https://github.com/arkon/ng-sidebar/blob/master/src/sidebar.module.ts#L13

Use this instead: 

```ts
static forRoot(): ModuleWithProviders {
    return {
      ngModule: SidebarModule,
      providers: [SidebarService]
    };
  }
```

read more: https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root

**Comment by arkon** [comment]
Added in 282c8ea4989cf1a03d2ab92cb5c3f8e133d66394

**Comment by tsm91** [comment]
This one u got wrong https://github.com/arkon/ng-sidebar/commit/282c8ea4989cf1a03d2ab92cb5c3f8e133d66394. Check comments and read angular docs.
