### ISSUE TITLE
Problems with AOT

### ISSUE THREAD

**Issue by JMarques007** [arkon/ng-sidebar#40]
Problems with AOT:
Error at /aot/node_modules/ng-sidebar/lib/sidebar-container.component.ngfactory.ts:93:44: Property '_sidebars' is private and only accessible within class 'SidebarContainer'.
Error at /aot/node_modules/ng-sidebar/lib/sidebar-container.component.ngfactory.ts:194:44: Property '_showBackdrop' is private and only accessible within class 'SidebarContainer'.
Error at /aot/node_modules/ng-sidebar/lib/sidebar-container.component.ngfactory.ts:197:44: Property '_getStyles' does not exist on type 'SidebarContainer'.
Error at /aot/node_modules/ng-sidebar/lib/sidebar.component.ngfactory.ts:282:18: Property '_elSidebar' is private and only accessible within class 'Sidebar'.
Error at /aot/node_modules/ng-sidebar/lib/sidebar.component.ngfactory.ts:304:44: Property '_getTransformStyle' does not exist on type 'Sidebar'.
Error at /aot/app/home/home.component.ngfactory.ts:188:44: Property '_sidebars' is private and only accessible within class 'SidebarContainer'.

Because private, protected accessors should be changed to public for any members accessed from template

**Comment by arkon** [comment]
Published v3.2.1 to NPM with fixes.
