### ISSUE TITLE
Keyclose=false ignored.

### ISSUE THREAD

**Issue by mikerhyssmith** [arkon/ng-sidebar#41]
We are using the ng-sidebar with the keyClose input set to false and keycode left as default however the sidebar is still closing when the escape key is pressed.

**Comment by arkon** [comment]
Is it set to `true` at any point?

**Comment by mikerhyssmith** [comment]
keyClose is always set to false in the html we can also see that ng-reflect-key-close is always set to false once angulars bootstrapped.

**Comment by arkon** [comment]
Hmm, so if you set `keyCode` to something else (e.g. `65` for the "a" key), does pressing "a" close it too?

**Comment by mikerhyssmith** [comment]
When we set keyCode to 65 neither "a" or "esc" will close the sidebar. If we remove keyCode again and leave it as default "esc" will close the sidebar.

**Comment by mikerhyssmith** [comment]
It looks like as we are writing keyClose="false" when it does the boolean check of keyClose this is evaluating to truthy. Would it be possible to support inputs in this form and parsing them as booleans ?

**Comment by arkon** [comment]
Do you mean you're passing it as a string? Just passing `false` shouldn't be truthy.

**Comment by mikerhyssmith** [comment]
It looks like we should've been using [keyClose]="false" rather than keyClose="false" as this will  pass through the boolean value rather than the string value.  We assumed the second would be ok as we weren't binding to a property on the component !

**Comment by arkon** [comment]
Ah, yes. It expects an actual boolean value, so that is required. :)
