### ISSUE TITLE
Sidebar does not work correctly in IE 11 in dock mode

### ISSUE THREAD

**Issue by Akkusativobjekt** [arkon/ng-sidebar#43]
I noticed while testing my own app that the sidebar does not work correctly in the internet explorer. I retried it with your showcase sidebar and the bug does also occur.

When the mode is set to dock, the sidebar is shown correctly:
![dock initial cutted](https://cloud.githubusercontent.com/assets/5674024/22826867/f22bfe30-ef94-11e6-86f4-7a7347b1a86b.png)

Then after you open and close it, the content of the main page is  behind the sidebar, instead of being pushed.
![dock after cutted](https://cloud.githubusercontent.com/assets/5674024/22826897/1ace5612-ef95-11e6-978c-dceeaaa6ad5e.png)

The system I use is  Windows 7 64 bit with the Internet Explorer 11 .
The push mode per se works correctly in the ie.

**Comment by arkon** [comment]
Appears to be a bug in IE/Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/104773/

I'll keep looking into it to see if there's a workaround.

**Comment by arkon** [comment]
Published v3.2.2, which should work in IE/Edge.
