### ISSUE TITLE
Is ng-sidebar unstyled

### ISSUE THREAD

**Issue by jculverwell** [arkon/ng-sidebar#44]
I've installed ng-sidebar in a clean angular-cli project (beta 30) and it comes up unstyled, as per the picture below?  Is this by design or have I missed something?

![ngsidebar](https://cloud.githubusercontent.com/assets/518738/22853402/7ebafa4e-f0a9-11e6-92ca-eef0db15c277.png)

I followed the instructions in the readme.md.

I installed using `npm install ng-sidebar --save`

My app.component.html file looks like this:

```    <ng-sidebar-container>
       <!-- A sidebar -->
      <ng-sidebar [(opened)]="_opened">
        <p>Sidebar contents</p>
      </ng-sidebar>

     <!-- Page content -->
      <button (click)="_toggleSidebar()">Toggle sidebar</button>
   </ng-sidebar-container>
```

My app.component.ts file looks like this:

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app works!';
  private _opened: boolean = false;

  private _toggleSidebar() {
    this._opened = !this._opened;
  }
}

```

And my app.module.ts looks like this:

```
import { SidebarModule } from 'ng-sidebar';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    SidebarModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Thank you for a great project and welcome your thoughts.

**Comment by arkon** [comment]
Yes, it comes with nearly no styling. Other than a default white background and the appropriate positioning, you're given complete freedom to style it however you like.

The [demo](https://github.com/arkon/ng-sidebar/blob/master/demo/src/demo/demo.component.ts#L7) has some very [basic styles](https://github.com/arkon/ng-sidebar/blob/master/demo/src/style/style.scss#L43) applied to it.

**Comment by jculverwell** [comment]
Thank you, added the styles from the demo and it works perfectly.  Thanks again for your help.

**Comment by YogeshBorkhade** [comment]
it doesn't work for me. sidebar is not loading.
i followed the whole procedure but still unable to see side bar, content out side the <ng-sidebar-container> is displays properly

**Comment by arkon** [comment]
I should really add this to the README, but does #100 help, @YogeshBorkhade ?

**Comment by sergiuchiorean** [comment]
it doesn't apply the style on custom class. I used exactly as in demo example 
[sidebarClass]="'demo-sidebar'".
I'm using angular 5

**Comment by sergiuchiorean** [comment]
never mind. i got it working with :host /deep/

**Comment by thariesl** [comment]
Hey people, i downloaded ng-sidebar a while ago now but i simply don't know how to use the classes and styles listed on: github.com/arkon/ng-sidebar.. No #100 does not help and the Angular documentation neither. I am probably  too big of a noob but please help me. It shows up, i can also open it but i don't know where to apply anything.

HTML: 
```
<div class="container">
            <ng-sidebar-container>
                <ng-sidebar [(opened)]="_opened">
                    <p>Sidebar contents</p>
                </ng-sidebar>
                <div ng-sidebar-content>
                    <button (click)="_toggleSidebar()">Toggle sidebard</button>
                </div>
            </ng-sidebar-container>
</div>
```
TS:
```
export class HeaderComponent implements OnInit {

    private _opened:boolean = false;
    private _toggleSidebar(){
        this._opened = !this._opened;
    }
}
```
CSS:
```
ng-sidebar-container{
    height:50px;
}
```
