### ISSUE TITLE
Make sidebar responsive

### ISSUE THREAD

**Issue by sharok** [arkon/ng-sidebar#47]
Hi. It would be great if you can add option for automatic close sidebar when screen size is < 640px(for example) .

**Comment by arkon** [comment]
You could probably just implement this yourself:

```html
<div (window.resize)="_onResize($event)">
  <ng-sidebar-container>
    <ng-sidebar #sidebar>
       ...
    </ng-sidebar>
  </ng-sidebar-container>
</div>
```

```typescript
_onResize(e: Event) {
  if (window.innerWidth < 640px && this.sidebar.opened) {
    this.sidebar.close();
  }
}
```

I'm sort of paraphrasing a bit, but I _think_ something like that would work.

**Comment by sharok** [comment]
Yeah, I did it in the same way. I just thought about having that feature
out of the box.

**Comment by arkon** [comment]
I'll consider it. I'm thinking of how it'd look like as an option. Something like `[autoCollapse]="'640px'"`? I guess the value would indicate either the window width or height depending on the positioning of the sidebar. It might also be of interest to throttle the resize event handler.

**Comment by sharok** [comment]
Yeah, `[autoCollapse]` is good name. Probably, it's better to create two options, one for width and one for height for better customizing, but it's details.

**Comment by arkon** [comment]
`[autoCollapseHeight]` and `[autoCollapseWidth]` have been added in v3.4.0.

**Comment by ball6847** [comment]
I want to collapse based on width but in the opposite direction, collapse if scren width is larger than we want.

Any idea ?

**Comment by arkon** [comment]
Make a new issue for a feature request.
