### ISSUE TITLE
Styles on ng-sidebar not working

### ISSUE THREAD

**Issue by deepikadurs** [arkon/ng-sidebar#48]
I am newbie to Angular2. Could you help me with below issue.
Stylings marked via the class mentioned as sidebarClass isn't getting applied.
![ng-sidebar](https://cloud.githubusercontent.com/assets/7833944/23088449/8beeeae0-f531-11e6-9007-3a5724f87539.PNG)

**Comment by arkon** [comment]
I'm not entirely sure what your screenshot is supposed to show, but #20 might help.

**Comment by deepikadurs** [comment]
I downloaded the demo code and tried running it. When I did that, styles specified via sidebarClass, demo-sidebar, was not getting applied. Screenshot was to showcase style-less sidebar.
Using /deep/ on the aside element of ng-sidebar worked for me.

**Comment by arkon** [comment]
That's weird. What browser are you using?

**Comment by deepikadurs** [comment]
I am using Chrome

**Comment by arkon** [comment]
That's really weird, it works perfectly fine in Chrome for me. I'll close this anyway since I'm not entirely sure what's wrong but feel free to reopen it if as needed.
