### ISSUE TITLE
Is it possible to put the page content outside of the wrapper?

### ISSUE THREAD

**Issue by tosehee75** [arkon/ng-sidebar#52]
```
<ng-sidebar-container>
  <!-- A sidebar -->
  <ng-sidebar [(opened)]="_opened">
    <p>Sidebar contents</p>
  </ng-sidebar>
  Test
</ng-sidebar-container>

```

Instead of above,

```
<ng-sidebar-container>
  <!-- A sidebar -->
  <ng-sidebar [(opened)]="_opened">
    <p>Sidebar contents</p>
  </ng-sidebar>
</ng-sidebar-container>

Content here..
```

That way, I can create my own component much easier by encapsulating the <np-sidebar-container> with it.

THanks.

**Comment by tosehee75** [comment]
My bad. Works as is. I thought it was limited to putting the contents within the wrapper.

**Comment by arkon** [comment]
Yes, you can put things outside of the container, but certain features might not work as expected, like the backdrop, or modes other than the default "over".
