### ISSUE TITLE
Two Side bars and getting errors

### ISSUE THREAD

**Issue by tosehee75** [arkon/ng-sidebar#53]
Thanks for the component. We are building a proto-type app, and it's finding its spot in a good place.

I was able to utilize the sidebar on the right side and it works fine.

However, when I tried to add "two" sidebars with different #, I get this odd issue.

```
Error: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at ExpressionChangedAfterItHasBeenCheckedError.ZoneAwareError (zone.js:992)
    at ExpressionChangedAfterItHasBeenCheckedError.BaseError [as constructor] (errors.js:22)
    at new ExpressionChangedAfterItHasBeenCheckedError (errors.js:59)
    at checkBinding (view_utils.js:167)
    at Wrapper_NgControlStatus.checkHost (/InternalFormsSharedModule/NgControlStatus/wrapper.ngfactory.js:33)
    at View_NgTableComponent10.detectChangesInternal (/AppModule/NgTableComponent/component.ngfactory.js:715)
    at View_NgTableComponent10.AppView.detectChanges (view.js:425)
    at View_NgTableComponent10.DebugAppView.detectChanges (view.js:620)
    at ViewContainer.detectChangesInNestedViews (view_container.js:67)
    at View_NgTableComponent9.detectChangesInternal (/AppModule/NgTableComponent/component.ngfactory.js:845)
    at View_NgTableComponent9.AppView.detectChanges (view.js:425)
    at View_NgTableComponent9.DebugAppView.detectChanges (view.js:620)
    at ViewContainer.detectChangesInNestedViews (view_container.js:67)
    at CompiledTemplate.proxyViewClass.View_NgTableComponent0.detectChangesInternal (/AppModule/NgTableComponent/component.ngfa

```

The container for this is very simple one as below.

```
<ng-sidebar-container>
  <!-- A sidebar -->
  <ng-sidebar #bottombar
              [(opened)]="_displayed"
              [keyClose]="false"
              [position]="'bottom'"
              [mode]="'push'">
    Test

    <button>Test</button>
    <!--<button type="button" class="btn btn-secondary" (click)="bottombar.close()">Cancel</button>-->
    <!--&lt;!&ndash;<button type="button" class="btn btn-secondary btn-sm" (click)="submit()">Delete</button>&ndash;&gt;-->
    <!--<button type="button" class="btn btn-primary" (click)="submit()">Save</button>-->
  </ng-sidebar>
</ng-sidebar-container>
```

Am I doing something wrong here?

The "#" name for both sidebar are different. Above is "#bottombar", but the other one is called "sidebar"..

Any help is appreciated.

**Comment by arkon** [comment]
What's the other sidebar like? Is it in the same container? Does the error go away if either of the two sidebars are removed?

**Comment by tosehee75** [comment]
They are on their own containers and I tried putting them in one. Same result.

Removing one makes it work of course

**Comment by CatinhoCR** [comment]
@tosehee75 
Not sure if I understood this correctly, but I was able to include 2 sidebars in my project.
My mark up is as follows:
`<div class="fluid-container">
   
    <dashboard-header></dashboard-header>
    
    <div class="dashboard-content-zone">
        <ng-sidebar-container>
            
            <ng-sidebar [(opened)]="_qOpened" position="left" closeOnClickOutside="true" showBackdrop="true" dock="true" dockedSize="60px">
                
            </ng-sidebar>
            
            <button (click)="_toggleqSidebar()">Toggle sidebar</button>
        </ng-sidebar-container>
        </div>
</div>`

Naturally, the <dashboard-header> component has another `<ng-sidebar-container>` with it's own content.

**Comment by CatinhoCR** [comment]
@tosehee75 
Not sure if I understood this correctly, but I was able to include 2 sidebars in my project.
My mark up is as follows:

```
<div class="fluid-container">
    <dashboard-header></dashboard-header>
    <!-- main content zone -->
    <div class="dashboard-content-zone">
        <ng-sidebar-container>
            <!-- A sidebar -->
            <ng-sidebar [(opened)]="_qOpened" position="left" closeOnClickOutside="true" showBackdrop="true" dock="true" dockedSize="60px">
                <!-- some content here -->
            </ng-sidebar>
            <!-- Page content -->
            <button (click)="_toggleqSidebar()">Toggle sidebar</button>
        </ng-sidebar-container>
        </div>
</div>
```

Naturally, the ```<dashboard-header>``` component has another ```<ng-sidebar-container>``` with it's own content.

**Comment by arkon** [comment]
I was never able to reproduce this. If it's still happening with newer versions, feel free to reopen this.

**Comment by georgeos** [comment]
@CatinhoCR 
How do you include two ng-sidebars? I was trying to do the same but without success.

https://stackoverflow.com/questions/48699038/html-to-display-two-ng-sidebar

If you can help me, I'll appreciate. Thanks!

**Comment by arkon** [comment]
@georgeos You probably want both `<ng-sidebar>`s within the same `<ng-sidebar-container>`.

**Comment by georgeos** [comment]
Uffff thanks @arkon !

**Comment by ef32** [comment]
two ng-sidebars in the same <ng-sidebar-container> puts the mode attribute in a state if they are different, ultimately causing errors in application. I am using version 7.2.0. How can this be rectified please?

**Comment by arkon** [comment]
Open a new issue, and provide more details.

**Comment by ef32** [comment]
okay will do
