### ISSUE TITLE
[push mode] container width not updated when sidebar content changes

### ISSUE THREAD

**Issue by davidescr** [arkon/ng-sidebar#55]
Hi, I have a problem using the sidebar in "push" mode: if I change the sidebar's content, because it is dinamically generated, the width of the sidebar container is not updated.

Here is a simple Angular 2 component that shows the problem.
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div style="width:100%;display:flex">

	<!-- growing div -->
        <div style="flex-grow:1;background-color:#c7fdff;border:1px solid black;">
            I am a growing div
        </div>

        <!-- Container for sidebar(s) -->
        <ng-sidebar-container>

            <!-- A sidebar -->
            <ng-sidebar #sidebar
                [opened]="true"
                [mode]="_mode"
                [position]="'right'"
                [closeOnClickOutside]="false">

                <input type="checkbox" (click)="_toggleMode()" checked="true"> Push mode

                <div>
                    <button (click)="_changeText()">Change content</button>
                </div>

                <p>{{_content}}</p>
	    </ng-sidebar>

        </ng-sidebar-container>
    </div>
  `
})
export class AppComponent {
  _mode = 'push';
  _content = 'Some kind of a long content like Lorem Ipsum';
 
  _toggleMode() {
      if (this._mode === 'over') this._mode = 'push';
      else this._mode = 'over';
  }

  _changeText() {
      if (this._content === 'Simple content')
          this._content = 'Some kind of a long content like Lorem Ipsum';
      else
          this._content = 'Simple content';
  }
}
```
Clicking on the "change content" button the size of the growing div will not be updated (clicking 2 times on the checkbox "push mode", changing it to "over" and then to "push" again, will "resolve" the problem).

Using the Chrome's inspector tool I saw that there is a
`<div class="ng-sidebar__content" ... >`
with generated margins. Those not-updated-margins seem to be problem's cause.

Waiting for your reply,
Davide

PS beside that little issue, I think that your Sidebar is great!! :+1: thank you for sharing!

**Comment by arkon** [comment]
Thanks for reporting this, and also digging into it a little. You're right that the margins aren't automatically updated, but I'll need to think about how to handle that.

**Comment by davidescr** [comment]
Ok, thanks! I'll wait

Regards,
Davide

**Comment by arkon** [comment]
I decided to add a `triggerRerender()` function to the sidebar that can be manually called to trigger a re-render for the container, which should solve this issue in a somewhat roundabout way. I wanted to avoid using something like a MutationObserver since it doesn't support IE 10, and it also might be detrimental to performance if the sidebar has a lot of stuff inside it.
