### ISSUE TITLE
Output event example

### ISSUE THREAD

**Issue by rhodesy** [arkon/ng-sidebar#56]
Has anyone got an example for handling output events, e.g. handling when <ng-sidebar> openedChange is modified?

**Comment by arkon** [comment]
It'll likely be more useful to use the [events for open/close](https://github.com/arkon/ng-sidebar#outputs-1).

[The demo](https://github.com/arkon/ng-sidebar/blob/master/demo/src/demo/demo.component.ts#L22) has [basic examples](https://github.com/arkon/ng-sidebar/blob/master/demo/src/demo/demo.component.ts#L153).

**Comment by rhodesy** [comment]
That's great, thanks arkon! I should have looked a bit harder - pretty obvious now :)
