### ISSUE TITLE
Does not seem to work with "ng serve"

### ISSUE THREAD

**Issue by javaspeak** [arkon/ng-sidebar#57]
Hi Arkon,

I am a bit new to this so maybe I am missing something and this is not a bug.  Maybe it needs to be integrated in a different way.

Anyway as other users may also be newbies I thought I would raise this ticket for it could alert you to the kind of problems your user base is having.

I used @angular/cli to create a new angular 2 project as follows:

     ng new ngsidebarexample
     cd ngsidebarexample
     npm install angularjs --save
     ng serve

Then I edited my app.component.ts as follows:

    import { Component } from '@angular/core';

    @Component({
      selector: 'app-root',
      templateUrl: './app.component.html',
      styleUrls: ['./app.component.css']
    })
    export class AppComponent {
      title = 'app works!';

      private _opened: boolean = false;
 
      private _toggleSidebar() {
        this._opened = !this._opened;
      }
    }

I did not see any system js file so I thought I was not using it and so did not update it.  Your docs seem to indicate it is not mandatory according to your docs:

I updated my app.module.ts:

    import { BrowserModule } from '@angular/platform-browser';
    import { NgModule } from '@angular/core';
    import { FormsModule } from '@angular/forms';
    import { HttpModule } from '@angular/http';
    import { SidebarModule } from 'ng-sidebar'

    import { AppComponent } from './app.component';

    @NgModule({
      declarations: [
        AppComponent
      ],
      imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        SidebarModule.forRoot()
      ],
      providers: [],
        bootstrap: [AppComponent]
     })
     export class AppModule { }     

Then I opened browser at 

     http://localhost:4200/

I saw the:

    app works!
    Toggle Sidebar button
    
    Sidebar contents

If I click the sidebar button it disappeared but there was no sidebar

I think this example does not work with @anglular/cli project creation and ng serve

Not sure if this is a bug or I am completely ignorant about something?  Maybe this has to be integrated in a different way and does not work with "ng new" and "ng serve" ? 

Sorry in advance if I am wasting time.

Thank you for your time

**Comment by arkon** [comment]
SystemJS is indeed an optional way of doing it. Since you're using the CLI tool, that uses Webpack internally instead of SystemJS. I haven't really looked into the changes with Angular 4 and AOT, but I suspect there's something wrong on my end for that, so I'll need to look into it.

**Comment by javaspeak** [comment]
Thanks for the info

**Comment by Nox-404** [comment]
Can you post the app.component.html template, for me it worked with ng-cli

**Comment by arkon** [comment]
@Nox-404 I'm assuming you're asking @javaspeak ?

**Comment by javaspeak** [comment]
@Nox-404 and @arkon 

Thanks for your comments.

I ran 

    npm install --save ng-sidebar

again and this time it worked.

I may have previously somehow had an outdated previous version that did not work.

Thanks for your help.
