### ISSUE TITLE
Not working with angular 2

### ISSUE THREAD

**Issue by elega9t** [arkon/ng-sidebar#58]
Hi, 

I have used angular-seed https://mgechev.github.io/angular-seed

However, the slide menu does not seem to work. The slide menu stays on the page even on closed mode (screen shots attached)

The sample project is at:

https://github.com/elega9t/angular-seed-slide-menu

Thanks for your help
![sidebar-closed](https://cloud.githubusercontent.com/assets/4546883/24325394/f33bc3c4-118f-11e7-99ca-a78ca561eb8b.png)

![sidebar-open](https://cloud.githubusercontent.com/assets/4546883/24325395/f33ff75a-118f-11e7-9e38-c740dfca70c5.png)

**Comment by arkon** [comment]
This was actually a bug, so thanks for reporting it! I've published v3.4.2 with the fix.
