### ISSUE TITLE
Sidebar is initially visible on IE 11 when it should not be (regression from v2.0.0 to v3.x.x)

### ISSUE THREAD

**Issue by mircowidmer** [arkon/ng-sidebar#59]
After updating and migrating from v2.0.0 to v3.0.0 the following example (in top level app.component) results in an unwanted effect in Internet Explorer 11:
![internet-explorer-problem](https://cloud.githubusercontent.com/assets/1065341/24539300/31bb67be-15ee-11e7-8e18-70128e6e98df.gif)
Initially the sidebar is visible (for a short period of time) and gets hidden after the page started rendering. The effect is especially bad when the page rendering takes a bit longer than in this simple example. The sidebar is visible for a longer period of time before it gets hidden. This effect only occurs in IE 11 and v3.x.x, but did not occur in v2.0.0. As far as I can tell, this 'bug' affects all versions 3.x.x.

*app.component.html*
```
<h1>
  {{title}}
</h1>
<ng-sidebar-container>

  <!-- A sidebar -->
  <ng-sidebar [(opened)]="opened">
    <p>Sidebar contents</p>
  </ng-sidebar>

  <button (click)="toggleSidebar()">Toggle sidebar</button>

</ng-sidebar-container>

```

*app.component.ts*
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  opened = false;

  toggleSidebar() {
    this.opened = !this.opened;
  }
}
```

The code for version v2.0.0 (`open` instead of `opened` and no <ng-sidebar-container>) worked perfectly before. Is there a bug or something else incorrectly in this example?

**Comment by arkon** [comment]
Thanks, I've verified that this indeed happens in the demo, and only in IE (also tested in the latest stable versions of Chrome, Firefox, Safari, and Edge).

It must have happened when I switched back to relying on CSS transforms for showing the sidebar, so I'll try to see if it can be fixed.

**Comment by arkon** [comment]
v3.4.3 published to NPM with the fix.

For reference, https://github.com/almasaeed2010/AdminLTE/issues/430 is the same kind of problem.
