### ISSUE TITLE
Add mode to push/slide entire content over

### ISSUE THREAD

**Issue by guzuomuse** [arkon/ng-sidebar#60]
when you use mode push,the content be pushed aside with a margin changed
but,if your content is responsive , the appearance be changed also!
i use :host >>> .ng-sidebar {position:absolute} but not work!
how to deal with this?
thank you

**Comment by arkon** [comment]
Hi @guzuomuse, is there any chance you can provide screenshots of what you mean?

**Comment by guzuomuse** [comment]
hi,@arkon thanks for your reply
failed to upload images here 
i add the links,you can check it . 

[img1](https://drive.google.com/file/d/1HoXpSPdNaEeV0jGLxPA0rcKLP6dQrrE19g/view)
[img2](https://drive.google.com/open?id=1lcJekMjrREK3D1ngET2R_SfjkazhnJwAWw)
please compare these two files. thanks

**Comment by arkon** [comment]
Added locally. Will be released soon.

**Comment by guzuomuse** [comment]
awaiting...:)

**Comment by guzuomuse** [comment]
wooo!....released! thanks.
