### ISSUE TITLE
Push mode doesn't animate the content

### ISSUE THREAD

**Issue by Nox-404** [arkon/ng-sidebar#65]
When using the Push mode with animation, the sidebar is animated but the content isn't.
It feels weird, when opening the sidebar, the content shift instantly and the sidebar smoothly get in place...

Also, it could be useful to be able to control those two animations.

**Comment by Nox-404** [comment]
As a temporary fix I used this style on the container.

```css
-webkit-transition: margin 0.3s cubic-bezier(0, 0, 0.3, 1);
transition: margin 0.3s cubic-bezier(0, 0, 0.3, 1);
```

But it's not really smooth because in push mode the sidebar is a bit further (110%) so the content goes into position faster than the sidebar.

But still, I can't override any css... I'd like to be able to change the animation and style, is there a way ?

**Comment by arkon** [comment]
Fixed locally. Will be released soon.
