### ISSUE TITLE
I am having error webpack

### ISSUE THREAD

**Issue by maxto024** [arkon/ng-sidebar#66]
i just install 
npm install --save ng-sidebar

I am using webpack

i get this error

ERROR in [at-loader] ./node_modules/ng-sidebar/lib/sidebar-container.component.d.ts:1:106 
    TS2305: Module '"/media/maxto/LuulSolutions/luul_projects/population/gateway/node_modules/@angular/core/index"' has no exported member 'Renderer2'.

**Comment by arkon** [comment]
ng-sidebar v4.x requires Angular 4. I'll be trying to make that requirement more lenient though.

**Comment by loongdefect** [comment]
Can't use with angular-cli rc1 and angular 2?

**Comment by arkon** [comment]
ng-sidebar v4.1.0 should be okay with Angular 2.3.0+ now.
