### ISSUE TITLE
routerLinkActive always "home" active

### ISSUE THREAD

**Issue by ninomirabile** [arkon/ng-sidebar#68]
here my code.
when i open the sidebar and select an option (e.g. contatori). close sidebar. open again sidebar, "home" is active, not my actualy route.

` <ng-sidebar
       [(opened)]="_opened"
       [mode]="'push'"
       [autoCollapseHeight]="_autoCollapseHeight"
       [autoCollapseWidth]="_autoCollapseWidth"
       [closeOnClickOutside]="_closeOnClickOutside"
       [showBackdrop]="_showBackdrop">
        <ul>
            <li role="presentation" routerLinkActive="active"
            [routerLinkActiveOptions]="{exact: true}" >
              <a routerLink="/" (click)="_toggleSidebar()">home</a>
              </li>
            <li role="presentation" routerLinkActive="active">
              <a routerLink="/prezzi" (click)="_toggleSidebar()">prezzi</a>
              </li>
            <li role="presentation" routerLinkActive="active">
              <a routerLink="/carico" (click)="_toggleSidebar()">carico</a>
              </li>
            <li role="presentation" routerLinkActive="active">
              <a routerLink="/contatori" (click)="_toggleSidebar()">contatori</a>
              </li>
            <li role="presentation" routerLinkActive="active">
              <a routerLink="/fatture" (click)="_toggleSidebar()">fatture</a>
              </li>
            <li role="presentation" routerLinkActive="active">
              <a routerLink="/impostazioni" (click)="_toggleSidebar()">impostazioni</a>
              </li>
        </ul>
    
      </ng-sidebar>`

**Comment by arkon** [comment]
You can try adding `[routerLinkActiveOptions]="{ exact: true }"` to your home anchor. This is more [an issue with Angular's router](https://github.com/angular/angular/issues/8397#issuecomment-237314970) though, not this sidebar.
