### ISSUE TITLE
Bug? input elements + autofocus and animate

### ISSUE THREAD

**Issue by Ketec** [arkon/ng-sidebar#70]
Came across a rather annoying issue - if i added any input element inside the sidebar, it did not animate when opened - instead it animated the rest of the page.

I have set the sidebar position to absolute instead of fixed (needs to stay inside the container and scroll out of view if container is scrolled). Its inside a flex row container with panel to the left and sidebar to the right - hovers over the left panel when opened.

It seems like it selects the first input element it comes across before animating and that's when it breaks.

**Comment by arkon** [comment]
What `mode` is the sidebar set to? What browser(s) does this happen in? If possible, it'd be great to see some of the template code.

**Comment by Ketec** [comment]
Mode is 'over' - but also happens with 'push'.
A mockup of the component template (its rather complicated + cant copy paste all of it and make it public)

```
<div>
    <div>
        <div>grid-header</div>
        <div>
            <datatable-component
            </datatable-component>
        </div>
    </div>
    <ng-sidebar-container>
        <ng-sidebar
            [(opened)]="opened"
            position=right
            [autoFocus]=false
            [mode]="'over'"
        #ngsidebar>
            <div>header</div>
            <div>content</div>
        </ng-sidebar>
    </ng-sidebar-container>
</div>
```
main div is a row flexbox + 100% height. the grid on the left, sidebar to the right.

the css that overrides sidebar behavior:
```
.ng-sidebar {
    box-shadow: -4px 0px 3px -1px #e5e5e5;
    background-color: #f3f3f4 !important;
    overflow: hidden !important;
    position: absolute !important;
}

```
It only seems to happen with <input> elements when autoFocus true and the element is initially visible - if its hidden and enabled later - it's fine.

**Comment by arkon** [comment]
So if I understand this correctly, the sidebar simply doesn't open (if it tries to focus an input element inside the sidebar), but the content still gets pushed over? Are there any errors in the console when that happens?

**Comment by arkon** [comment]
Nevermind, I reproduced it based on the information you gave. This is indeed a bug, although I still need to investigate as to why it happens. Is there any reason why you're not putting the `<datatable-component>` and other content inside the `<ng-sidebar-container>` though?

**Comment by Ketec** [comment]
I figured that it was just part of the sidebar to contain the sidebar itself.

**Comment by arkon** [comment]
@Ketec Nope, it's meant to contain both the sidebars and the page content so it can correctly animate them. I'm pretty sure this issue would be fixed if you moved the content into the container, but I'll be looking into it anyway.
