### ISSUE TITLE
Sidebar does not work after the angular 4 upgrade

### ISSUE THREAD

**Issue by mstfsnkl** [arkon/ng-sidebar#73]
Hello, first of all thank you for your great effort on developing this component. I'm loving it. It has been functioning very well in angular 2 but after i upgraded my app to angular 4 it has stopped functioning. 

`ERROR ObjectUnsubscribedError {originalStack: "Error: object unsubscribed↵    at ObjectUnsubscrib…tp://192.168.1.55:1871/vendor.bundle.js:19075:18)", zoneAwareStack: "Error: object unsubscribed↵    at ObjectUnsubscrib…tp://192.168.1.55:1871/vendor.bundle.js:19075:18)", stack: "Error: object unsubscribed↵    at ObjectUnsubscrib…tp://192.168.1.55:1871/vendor.bundle.js:19075:18)", message: "object unsubscribed", name: "ObjectUnsubscribedError"…}message: "object unsubscribed"name: "ObjectUnsubscribedError"ngDebugContext: DebugContext_ngErrorLogger: function ()originalStack: "Error: object unsubscribed↵    at ObjectUnsubscribedError.ZoneAwareError (http://192.168.1.55:1871/polyfills.bundle.js:3771:33)↵    at new ObjectUnsubscribedError (http://192.168.1.55:1871/vendor.bundle.js:67297:26)↵    at EventEmitter.Subject._trySubscribe (http://192.168.1.55:1871/vendor.bundle.js:37453:19)↵    at EventEmitter.Observable.subscribe (http://192.168.1.55:1871/vendor.bundle.js:14724:27)↵    at EventEmitter.subscribe (http://192.168.1.55:1871/vendor.bundle.js:4061:43)↵    at http://192.168.1.55:1871/vendor.bundle.js:66215:37↵    at Array.forEach (native)↵    at QueryList.forEach (http://192.168.1.55:1871/vendor.bundle.js:5964:65)↵    at SidebarContainer._subscribe (http://192.168.1.55:1871/vendor.bundle.js:66214:28)↵    at http://192.168.1.55:1871/vendor.bundle.js:66128:19↵    at SafeSubscriber.schedulerFn [as _next] (http://192.168.1.55:1871/vendor.bundle.js:4051:36)↵    at SafeSubscriber.__tryOrUnsub (http://192.168.1.55:1871/vendor.bundle.js:19222:16)↵    at SafeSubscriber.next (http://192.168.1.55:1871/vendor.bundle.js:19171:22)↵    at Subscriber._next (http://192.168.1.55:1871/vendor.bundle.js:19111:26)↵    at Subscriber.next (http://192.168.1.55:1871/vendor.bundle.js:19075:18)"stack: "Error: object unsubscribed↵    at ObjectUnsubscribedError.ZoneAwareError (http://192.168.1.55:1871/polyfills.bundle.js:3771:33)↵    at new ObjectUnsubscribedError (http://192.168.1.55:1871/vendor.bundle.js:67297:26)↵    at EventEmitter.Subject._trySubscribe (http://192.168.1.55:1871/vendor.bundle.js:37453:19)↵    at EventEmitter.Observable.subscribe (http://192.168.1.55:1871/vendor.bundle.js:14724:27)↵    at EventEmitter.subscribe (http://192.168.1.55:1871/vendor.bundle.js:4061:43)↵    at http://192.168.1.55:1871/vendor.bundle.js:66215:37↵    at Array.forEach (native)↵    at QueryList.forEach (http://192.168.1.55:1871/vendor.bundle.js:5964:65)↵    at SidebarContainer._subscribe (http://192.168.1.55:1871/vendor.bundle.js:66214:28)↵    at http://192.168.1.55:1871/vendor.bundle.js:66128:19↵    at SafeSubscriber.schedulerFn [as _next] (http://192.168.1.55:1871/vendor.bundle.js:4051:36)↵    at SafeSubscriber.__tryOrUnsub (http://192.168.1.55:1871/vendor.bundle.js:19222:16)↵    at SafeSubscriber.next (http://192.168.1.55:1871/vendor.bundle.js:19171:22)↵    at Subscriber._next (http://192.168.1.55:1871/vendor.bundle.js:19111:26)↵    at Subscriber.next (http://192.168.1.55:1871/vendor.bundle.js:19075:18)"zoneAwareStack: "Error: object unsubscribed↵    at ObjectUnsubscribedError.ZoneAwareError (http://192.168.1.55:1871/polyfills.bundle.js:3771:33)↵    at new ObjectUnsubscribedError (http://192.168.1.55:1871/vendor.bundle.js:67297:26)↵    at EventEmitter.Subject._trySubscribe (http://192.168.1.55:1871/vendor.bundle.js:37453:19)↵    at EventEmitter.Observable.subscribe (http://192.168.1.55:1871/vendor.bundle.js:14724:27)↵    at EventEmitter.subscribe (http://192.168.1.55:1871/vendor.bundle.js:4061:43)↵    at http://192.168.1.55:1871/vendor.bundle.js:66215:37↵    at Array.forEach (native)↵    at QueryList.forEach (http://192.168.1.55:1871/vendor.bundle.js:5964:65)↵    at SidebarContainer._subscribe (http://192.168.1.55:1871/vendor.bundle.js:66214:28)↵    at http://192.168.1.55:1871/vendor.bundle.js:66128:19↵    at SafeSubscriber.schedulerFn [as _next] (http://192.168.1.55:1871/vendor.bundle.js:4051:36)↵    at SafeSubscriber.__tryOrUnsub (http://192.168.1.55:1871/vendor.bundle.js:19222:16)↵    at SafeSubscriber.next (http://192.168.1.55:1871/vendor.bundle.js:19171:22)↵    at Subscriber._next (http://192.168.1.55:1871/vendor.bundle.js:19111:26)↵    at Subscriber.next (http://192.168.1.55:1871/vendor.bundle.js:19075:18)"__proto__: Error
View_AppComponent_0 @ AppComponent.html:1
proxyClass @ compiler.es5.js:13999
DebugContext_.logError @ core.es5.js:12946
ErrorHandler.handleError @ core.es5.js:1144
next @ core.es5.js:4754
schedulerFn @ core.es5.js:3828
SafeSubscriber.__tryOrUnsub @ Subscriber.js:236
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3814
NgZone.triggerError @ core.es5.js:4185
onHandleError @ core.es5.js:4146
ZoneDelegate.handleError @ zone.js:369
ZoneDelegate.hasTask @ zone.js:421
ZoneDelegate._updateTaskCount @ zone.js:438
Zone._updateTaskCount @ zone.js:262
Zone.runTask @ zone.js:182
drainMicroTaskQueue @ zone.js:591
AppComponent.html:1 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 4, nodeDef: Object, elDef: Object, elView: Object}component: (...)componentRenderElement: (...)context: (...)elDef: ObjectelOrCompView: (...)elView: Objectinjector: (...)nodeDef: ObjectnodeIndex: 4providerTokens: (...)references: (...)renderNode: (...)view: Object__proto__: Object
View_AppComponent_0 @ AppComponent.html:1
proxyClass @ compiler.es5.js:13999
DebugContext_.logError @ core.es5.js:12946
ErrorHandler.handleError @ core.es5.js:1149
next @ core.es5.js:4754
schedulerFn @ core.es5.js:3828
SafeSubscriber.__tryOrUnsub @ Subscriber.js:236
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3814
NgZone.triggerError @ core.es5.js:4185
onHandleError @ core.es5.js:4146
ZoneDelegate.handleError @ zone.js:369
ZoneDelegate.hasTask @ zone.js:421
ZoneDelegate._updateTaskCount @ zone.js:438
Zone._updateTaskCount @ zone.js:262
Zone.runTask @ zone.js:182
drainMicroTaskQueue @ zone.js:591`
`AppComponent.html:1 ERROR CONTEXT 
DebugContext_ {view: Object, nodeIndex: 4, nodeDef: Object, elDef: Object, elView: Object}
component
:
(...)
componentRenderElement
:
(...)
context
:
(...)
elDef
:
Object
elOrCompView
:
(...)
elView
:
Object
injector
:
(...)
nodeDef
:
Object
nodeIndex
:
4
providerTokens
:
(...)
references
:
(...)
renderNode
:
(...)
view
:
Object
__proto__
:
Object
View_AppComponent_0	@	AppComponent.html:1
proxyClass	@	compiler.es5.js:13999
DebugContext_.logError	@	core.es5.js:12946
ErrorHandler.handleError	@	core.es5.js:1149
next	@	core.es5.js:4754
schedulerFn	@	core.es5.js:3828
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:236
SafeSubscriber.next	@	Subscriber.js:185
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3814
NgZone.triggerError	@	core.es5.js:4185
onHandleError	@	core.es5.js:4146
ZoneDelegate.handleError	@	zone.js:369
ZoneDelegate.hasTask	@	zone.js:421
ZoneDelegate._updateTaskCount	@	zone.js:438
Zone._updateTaskCount	@	zone.js:262
Zone.runTask	@	zone.js:182
drainMicroTaskQueue	@	zone.js:591
`

This is the error I get when I run the component on my app. <ng-sidebar-container> This seems to be the problematic parts but I am not really sure what is it really about. 

Could you please help me with this issue? Thank you.

**Comment by arkon** [comment]
Could you try v4.2.3? It's hard to tell exactly what's going on in your case though.

**Comment by arkon** [comment]
Could you show the template with the sidebar, and possibly any JS code that has to do with the sidebar (e.g. event subscription)?

**Comment by arkon** [comment]
Frankly, I don't see anything wrong with your code. This also isn't an inherit issue of using the sidebar with Angular 4, since the demo also uses Angular 4. You could try removing content/options from the sidebar to a minimal state to see if that works.

**Comment by mstfsnkl** [comment]
https://pastebin.com/w2Ay1TRK

I figured out the problem thank you. Appearently It had something to do with ' routerLinkActive '  When I remove it, the sidebar works. Now I'm looking for a way to implement it again without breaking it.  Do you have any idea about that?

**Comment by arkon** [comment]
I'm unsure about that, sorry. [This issue](https://github.com/angular/angular/issues/8072) could be related.
