### ISSUE TITLE
Content is pushed only after screen resize

### ISSUE THREAD

**Issue by renannobile** [arkon/ng-sidebar#74]
Title says it all.

The content is only pushed after I resize the screen. 

```html
<ng-sidebar-container fxLayout="row">
    <ng-sidebar #sidebar [(opened)]="_opened" [mode]="mode" autoCollapseWidth="959">
        <p>Sidebar contents</p>
    </ng-sidebar>

    <div class="content" fxFlex="100">
        <div class="top">

        </div>

        <div class="main">
            <router-outlet></router-outlet>
        </div>
    </div>
</ng-sidebar-container>
```

That's my template

```typescript
import { Component, OnInit, ViewChild } from '@angular/core';

@Component({
    selector: 'app-layout',
    templateUrl: './layout.component.html',
    styleUrls: ['./layout.component.scss']
})
export class LayoutComponent implements OnInit {
    @ViewChild('sidebar') sidebar;

    private _opened: boolean;

    private mode = 'push';

    constructor() {
    }

    ngOnInit() { }

    private _toggleSidebar() {
        this._opened = !this._opened;
    }
}
```
And that's the component.

When I debug on ngOnInit(), the configurations are set to default (mode is over, no autoClose).

**Comment by arkon** [comment]
Are you debugging the `ngOnInit()` of the actual Sidebar component?

**Comment by renannobile** [comment]
No, I was debugging my own component's ngOnInit().

**Comment by arkon** [comment]
@renannobile I don't really see any reason why the Sidebar's input options wouldn't be taking effect properly. Unfortunately, setting breakpoints in your own component's `ngOnInit()` won't reveal much.

**Comment by arkon** [comment]
Sounds like a change detection issue on your end. Closing this for now, feel free to reopen if it still happens.
