### ISSUE TITLE
feature request: add isOpen method to the SidebarService

### ISSUE THREAD

**Issue by sfabriece** [arkon/ng-sidebar#75]
It would be desirable to know when the menu is open from a component that doesn't have access to the menu.

**Comment by arkon** [comment]
This sort of leads to the question of how the service is meant to be used if there's multiple sidebars being used. As it is right now, it doesn't really quite make sense either (e.g. if there's 2 sidebars, and you fire off the `open()` function, are both supposed to open?), so I'm a bit hesitant on adding this in before really thinking about that.

**Comment by sfabriece** [comment]
I'm having trouble finding out how to toggle the menu, from a component that is loaded via the router.

I've tried this: 

`
this.sidebarService.onOpen(() => {
      console.log('menu open');
    }`
 But it is not printing the text. Wasn't the service mean't to be use that way?

**Comment by arkon** [comment]
Calling `this.sidebarService.open();` should actually toggle it.

**Comment by sfabriece** [comment]
Actually, the problem i'm having is that I don't know the state of the menu, so that I can chose to call `open()` or `close()`. Adding a `toggle` method would solve my problem.

**Comment by arkon** [comment]
@Sifawm You seem to be more familiar with how services work in general. Do you have an idea on how this might be implemented? I can't really wrap my head around how the service would do this, since there isn't an apparent one-to-one relation between a service and a sidebar.

**Comment by arkon** [comment]
I'm opting to remove to the service instead since I don't really think it makes sense in the context of having multiple sidebars.
