### ISSUE TITLE
Push Mode Squeezes Content

### ISSUE THREAD

**Issue by panumsol** [arkon/ng-sidebar#76]
The push mode squeezes all the content. It should shift it without squeezing it therefore distorting it. 

Here is an example of how i think it should work: http://codepen.io/brettsmason/pen/GNwpPY

**Comment by arkon** [comment]
You can use `[mode]="'slide'"` for that.

**Comment by panumsol** [comment]
I must have missed that. Works great. Thanks

**Comment by arkon** [comment]
I actually forgot to add it to the README, although it was in the demo. I've added it to the README on GitHub for now. 👍
