### ISSUE TITLE
HammerJS issue

### ISSUE THREAD

**Issue by GuskiS** [arkon/ng-sidebar#78]
Because you don't have swipe support or touch in general, I added HammerJS to Angular as it has built in support for that. Everything works fine until I try to close sidebar by swiping again - it just doesn't trigger the event again because `aside` is somehow blocking it. It is triggered when I try to swipe on backdrop tho.

```ts
  @HostListener('body:swipeleft', ['$event.pointerType']) left(pointer: string) {
    if (pointer === 'touch' && this.mobile) {
      // dispatch to store
    }
  }
```
Although, it works on my Iphone SE, it doesn't work on android device I tested on. Same as for Chrome Dev tools touch thingy. Any ideas?

**Comment by arkon** [comment]
A quick Google search showed issues with hammerjs swipe support in some Android browsers, so I suspect it's something to do with that. Nothing comes to mind for the sidebar's implementation that would cause this.

**Comment by GuskiS** [comment]
I was testing on Android device but on Chrome browser. The issue was on Chrome Dev tools mobile mode also.
