### ISSUE TITLE
Slide mode and fixed to top

### ISSUE THREAD

**Issue by trzyna** [arkon/ng-sidebar#79]
I noticed that when using push mode, the sidebar stays fixed and doesn't scroll. When using slide mode, it doesn't stay fixed to top. Is there a way to have it stay fixed with slide mode?

**Comment by Sifawm** [comment]
I tried with the pull request #77 and it is ok. When you have push mode, the sidebar is fixed to top. When you have slide mode, not.

**Comment by arkon** [comment]
This is a bit of a side effect of `transform`-ing the entire thing over when sliding, which causes the `position: fixed` to apply to that layer context instead of the `body`. I'll tag this as a bug for now, but I doubt this will be fixed anytime soon.

**Comment by lexcaraig** [comment]
any update on this?

My issue was when i use `[mode]="push"` nothing happens.

**Comment by arkon** [comment]
@lexcaraig What do you mean nothing happens?

**Comment by jraaaaanger** [comment]
I'm seeing the same issue as @lexcaraig with `[mode]="'push'"`. The content inside `ng-sidebar-container` is pushed over properly but the sidebar itself doesn't move at all, not totally sure why. `[mode]="'slide'"` works as expected.

@arkon unsure if these are related, should I open a new issue for this?

**Comment by arkon** [comment]
Oh @lexcaraig you want either `[mode]="'push'"` or `mode="push"` because it's actually expecting the string `'push'`.

I'll need to check on what you're saying though, @jraaaaanger .

**Comment by jraaaaanger** [comment]
@arkon Thanks, let me know if you need more info

**Comment by arkon** [comment]
@jraaaaanger I made a separate issue for it: #93.

**Comment by arkon** [comment]
Fixed in v6.0.0.
