### ISSUE TITLE
class dont changed... 

### ISSUE THREAD

**Issue by akdenme** [arkon/ng-sidebar#80]
i want to make my sidebar push.. but when i put the ng-sidebar--push it didnt push...
also same for other class ng-sidebar--right but it didnt change also..

is this corect i do?

<ng-sidebar [(opened)]="_opened" class="ng-sidebar--push">
                  
                        <a closeSidebar>Closes the sidebar</a>
                        <p>asdasd</p>
               
</ng-sidebar>

**Comment by arkon** [comment]
No, you should be using inputs like `[mode]='"push"'`.
