### ISSUE TITLE
Combine over and dock mode

### ISSUE THREAD

**Issue by Jole83** [arkon/ng-sidebar#81]
Can I combine over and dock mode and how?

**Comment by arkon** [comment]
There isn't a way to do that, but it's a good idea for me to make it so dock is an alternative to normal closing for every mode instead.

**Comment by Jole83** [comment]
Your sidebar is wonderful. Can you tell me if I can do something to make this possible?
Or do you plan to make this possible soon?
Thank you.

**Comment by arkon** [comment]
@Jole83 I'm working on it! :)

**Comment by arkon** [comment]
This will be in the next release.
