### ISSUE TITLE
why not use @angular/animations

### ISSUE THREAD

**Issue by guzuomuse** [arkon/ng-sidebar#84]
i just want to know why not use @angular/animations?
thank you.

**Comment by arkon** [comment]
I originally started this library using CSS animations, then transitioned to using @angular/animations, but then eventually went back to CSS animations in af8a60c3a4536d1f22556a06535071481e3a31a6.

Basically, there were still compatibility issues with Angular's animation library (or the polyfill, not sure which) when using it in old browsers, and it also wasn't flexible enough to allow for dynamic animation states, which were required for handling certain things like docked mode. There's probably some clever ways of getting around those issues, but I didn't really think it was worth it.
