### ISSUE TITLE
'ng-sidebar-container' is not a known element:

### ISSUE THREAD

**Issue by Hassan121Cs** [arkon/ng-sidebar#87]
Hi,
I have tried to implement ng-sidebar multiple times but with no success. read all docs.
Trying with Angular v4 and es6.

Rest of the project is working fine without ng-sidebar

![image](https://cloud.githubusercontent.com/assets/17583020/26686003/23daff04-4705-11e7-8c64-a8218d510a36.png)

![image](https://cloud.githubusercontent.com/assets/17583020/26686245/d261e312-4705-11e7-809d-b8cc6f49dafa.png)

any clue will be very help full. 

Thank you all.

**Comment by Hassan121Cs** [comment]
seems as I included ng-sidebar in the wrong Angular-App. Having multiple apps in the project !

import { SidebarModule } from 'ng-sidebar';

**Comment by arkon** [comment]
@Hassan121Cs Is it fixed then?

**Comment by Hassan121Cs** [comment]
Yes, working good now. !!

**Comment by Hassan121Cs** [comment]
truly an amazing package for Angular 2 - 4.
with wonderful docs and demo, 
Have spend hours on evaluating different side menus but finally found the best on.
It would be more quicker to implement it with a working Plunder demo I guess.

What a great Work ! thank you for saving so many Jobs/lives 💯 🥇 

Thank you @arkon and your Great Team
