### ISSUE TITLE
Is it possible to have multiple sidebars?

### ISSUE THREAD

**Issue by CatinhoCR** [arkon/ng-sidebar#89]
Trying to have multiple sidebars within 1 page, could say a nested sidebar.

If I open each one of them everything works as expected, but when I close either one it also triggers the closing of the other sidebar. I changed the _opened variable name for one of them, and also the _toggleSidebar method name so it probably shouldn't be triggering for both of them.
Is there any way to overcome this?

The only workaround I've been able to come up with is by enabling the closeOnClickOutside to true on both of them, so it will close if clicked outside each one of them. But if I wanted to have this feature disabled then that's where the issue comes in.

**Comment by arkon** [comment]
Could I see some of your code? It seems to work fine for me.

**Comment by arkon** [comment]
Actually, I can reproduce this when I use the `closeSidebar` directive. Are you using that as well?

**Comment by CatinhoCR** [comment]
Hey there Arkon, thanks for the quick response.
Yes, I'm using the closeSidebar directive, you're right. That's when it triggers the close for both sidebars even if the variable and method names for each of those are different.

**Comment by arkon** [comment]
Fixed in v5.0.2.

**Comment by CatinhoCR** [comment]
@arkon 
Hey there, I know you already closed this, updated the package and everything works fine. Thanks about that.

I have a question though, didn't want to create a new issue for it. Is it ok if I ask it in here?

I'm trying to achieve 2 things:
1. Have 1 sidebar docked only to it's specific container, instead of the entire document/page.
2. Have nested toggable areas within that sidebar (see image for reference). So the docked part would have icons, each of those would toggle a secondary sub menu and then a third optional sub menu depending on chosen option.
![image](https://user-images.githubusercontent.com/10947007/26906082-1c5dfd10-4ba8-11e7-9e82-d1aa018b575c.png)

I am assuming none of these are contemplated in the project nor are achievable with the project as is right now?
