### ISSUE TITLE
How to override my css to ng-sidebar component?

### ISSUE THREAD

**Issue by pandaboycom** [arkon/ng-sidebar#96]
Hello, I want to override css to ng-sidebar component for change background color or add new css.

**Comment by pandaboycom** [comment]
Sorry, I know to use :host /deep/ ng-sidebar.

**Comment by arkon** [comment]
You can target the `.ng-sidebar` class. You'll need to use `!important` (or some other specificity trick) if you want to override [styles that are already defined](https://github.com/arkon/ng-sidebar/blob/master/src/sidebar.component.ts#L42) though.
